// ============================================================
// RoseStack Platform — Risk & Opportunities Seeded Data
// Agent 10: Risk & Opportunities Manager
// ============================================================

import type { RiskItem, OpportunityItem } from '@/shared/types';

// --- Helper ---
function riskRating(score: number) {
  if (score >= 16) return 'critical' as const;
  if (score >= 10) return 'high' as const;
  if (score >= 5) return 'medium' as const;
  return 'low' as const;
}

function opportunityRating(score: number) {
  if (score >= 16) return 'transformative' as const;
  if (score >= 10) return 'high' as const;
  if (score >= 5) return 'medium' as const;
  return 'low' as const;
}

// ============================================================
// RISKS
// ============================================================

export const SEEDED_RISKS: RiskItem[] = [
  // --- 1. Tariff & Revenue Risks ---
  {
    id: 'R-TAR-001',
    name: 'IOF rate reduction',
    category: 'tariff',
    description: 'Octopus reduces import/export spread on Intelligent Flux. Direct revenue reduction — model the impact of 10%, 20%, 50% spread compression.',
    probability: 4,
    impact: 4,
    score: 16,
    rating: riskRating(16),
    mitigationStrategy: 'Diversify revenue streams across multiple tariff types; monitor Octopus communications for early signals; model fallback revenue on Agile and Flux tariffs.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 8,
    triggerThreshold: 'Any published change to IOF import/export rates or spread narrowing >5%',
    contingencyPlan: 'Switch portfolio to Agile tariff with automated import/export optimisation; renegotiate homeowner payment if DSCR drops below 1.5x.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-TAR-002',
    name: 'IOF discontinuation',
    category: 'tariff',
    description: 'Octopus withdraws the IOF tariff entirely. Catastrophic — need to model fallback to Agile/Flux/standard tariffs and residual revenue.',
    probability: 3,
    impact: 5,
    score: 15,
    rating: riskRating(15),
    mitigationStrategy: 'Maintain fallback tariff models; ensure ESA contracts allow tariff switching; build relationship with Octopus commercial team for advance notice.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 6,
    triggerThreshold: 'Octopus removes IOF from tariff page or announces review of battery tariffs',
    contingencyPlan: 'Immediate migration to Agile + Flux; model residual revenue and adjust homeowner payments if needed.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-TAR-003',
    name: 'Agile price convergence',
    category: 'tariff',
    description: 'Day/night price spread narrows as more batteries enter the market. Reduces arbitrage opportunity across all time-of-use tariffs.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: riskRating(9),
    mitigationStrategy: 'Track Agile spread trends monthly; develop flexibility market revenue to offset narrowing spreads.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 6,
    triggerThreshold: 'Average daily Agile spread narrows below 15p/kWh for 30 consecutive days',
    contingencyPlan: 'Shift to flexibility-first revenue strategy using Piclo Flex and ENWL tenders.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-TAR-004',
    name: 'Export rate collapse',
    category: 'tariff',
    description: 'SEG and export rates driven down by oversupply of distributed generation. Impacts all export revenue streams.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: riskRating(9),
    mitigationStrategy: 'Maximise self-consumption in homeowner strategy; monitor SEG rate trends; explore direct PPA alternatives.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 6,
    triggerThreshold: 'SEG export rates drop below 10p/kWh',
    contingencyPlan: 'Shift strategy to self-consumption optimisation rather than export revenue.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-TAR-005',
    name: 'Saving Sessions cancelled',
    category: 'tariff',
    description: 'National Grid ESO discontinues Demand Flexibility Service. Removes £2,000-4,000/yr per home revenue stream.',
    probability: 2,
    impact: 4,
    score: 8,
    rating: riskRating(8),
    mitigationStrategy: 'Do not model Saving Sessions as core revenue in conservative projections; develop alternative flexibility revenue streams.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'implemented',
    residualScore: 4,
    triggerThreshold: 'ESO announces review or discontinuation of DFS',
    contingencyPlan: 'Replace with direct flexibility market participation via Piclo Flex or aggregator.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-TAR-006',
    name: 'Tariff eligibility change',
    category: 'tariff',
    description: 'Octopus changes battery size or MCS requirements for IOF. Could disqualify existing or planned systems.',
    probability: 2,
    impact: 4,
    score: 8,
    rating: riskRating(8),
    mitigationStrategy: 'Ensure all installations exceed current minimum requirements with margin; maintain MCS compliance documentation.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'in-progress',
    residualScore: 4,
    triggerThreshold: 'Octopus updates IOF eligibility criteria or MCS requirement changes',
    contingencyPlan: 'Retrofit systems to meet new requirements if economically viable; switch to alternative tariff if not.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-TAR-007',
    name: 'Standing charge increases',
    category: 'tariff',
    description: 'Significant standing charge rises eat into net revenue. Marginal but cumulative across portfolio.',
    probability: 3,
    impact: 2,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Monitor standing charge trends; factor into financial models with worst-case buffer.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'implemented',
    residualScore: 4,
    triggerThreshold: 'Standing charges exceed 80p/day',
    contingencyPlan: 'Absorb within operating margin; adjust homeowner payment structure if extreme.',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- 2. Energy Market Risks ---
  {
    id: 'R-MKT-001',
    name: 'Wholesale price crash',
    category: 'energy-market',
    description: 'Gas/electricity wholesale prices fall significantly (e.g. post-war peace, massive renewable buildout). Narrows arbitrage spread — all tariff rates are ultimately linked to wholesale.',
    probability: 2,
    impact: 4,
    score: 8,
    rating: riskRating(8),
    mitigationStrategy: 'Model revenue at multiple wholesale price levels; diversify into flexibility markets that increase in value when wholesale is low.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 6,
    triggerThreshold: 'Wholesale day-ahead average falls below £50/MWh for 3 consecutive months',
    contingencyPlan: 'Shift to flexibility-first strategy; low wholesale often means more renewables which increases grid volatility.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-MKT-002',
    name: 'Negative pricing frequency',
    category: 'energy-market',
    description: 'Increasing periods of negative wholesale prices. Could mean paying to export during some windows.',
    probability: 3,
    impact: 2,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Smart inverter scheduling to avoid export during negative price periods; use negative pricing windows for ultra-cheap charging.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 3,
    triggerThreshold: 'Negative pricing events exceed 100 hours per quarter',
    contingencyPlan: 'Negative pricing is actually an opportunity — charge at negative rates and discharge during positive spikes.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-MKT-003',
    name: 'Capacity market rule changes',
    category: 'energy-market',
    description: 'Ofgem/ESO change minimum thresholds or de-rate small batteries. Could exclude RoseStack portfolio from capacity market revenue.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Do not include capacity market revenue in base case projections; monitor CM rule consultations.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'implemented',
    residualScore: 3,
    triggerThreshold: 'Ofgem consultation on CM minimum thresholds for small-scale storage',
    contingencyPlan: 'Aggregate portfolio through licensed aggregator to meet minimum thresholds.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-MKT-004',
    name: 'Flexibility market saturation',
    category: 'energy-market',
    description: 'Too many batteries registered on Piclo Flex in ENWL territory. Drives down flexibility tender prices.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: riskRating(9),
    mitigationStrategy: 'Secure early positions in constrained substations; build ENWL relationship for preferred partner status.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 6,
    triggerThreshold: 'Flexibility tender prices in East Lancashire drop below £100/kW/yr',
    contingencyPlan: 'Diversify to other revenue streams; explore direct ENWL contracts outside Piclo.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-MKT-005',
    name: 'Grid balancing changes',
    category: 'energy-market',
    description: 'Shift from frequency response to other balancing mechanisms. Changes which services batteries can profitably provide.',
    probability: 2,
    impact: 2,
    score: 4,
    rating: riskRating(4),
    mitigationStrategy: 'Monitor NGESO balancing mechanism changes; ensure inverters can participate in multiple grid services.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 3,
    triggerThreshold: 'NGESO announces new balancing mechanism framework changes',
    contingencyPlan: 'Adapt portfolio to whatever balancing mechanism offers best returns.',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- 3. Regulatory & Policy Risks ---
  {
    id: 'R-REG-001',
    name: 'VAT on battery storage',
    category: 'regulatory',
    description: 'Government removes 0% VAT on residential battery installations. Increases capex by 20% overnight.',
    probability: 1,
    impact: 4,
    score: 4,
    rating: riskRating(4),
    mitigationStrategy: 'Monitor HMRC consultations; stockpile hardware before any announced change date.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'not-started',
    residualScore: 3,
    triggerThreshold: 'Government consultation on VAT for energy storage or clean tech',
    contingencyPlan: 'Factor 20% VAT into future models; may still be viable with hardware cost reductions.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-REG-002',
    name: 'Planning restrictions',
    category: 'regulatory',
    description: 'Local authority introduces planning requirements for large battery installations. Delays deployments, adds cost, some properties become ineligible.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Engage with Blackburn and Burnley planning teams proactively; ensure installations stay within permitted development rights.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'not-started',
    residualScore: 4,
    triggerThreshold: 'Any Lancashire council introduces battery-specific planning requirements',
    contingencyPlan: 'Pre-submit planning applications for future sites; build planning cost into capex model.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-REG-003',
    name: 'Fire safety regulation',
    category: 'regulatory',
    description: 'New regulations mandate minimum separation distances or enclosure standards. Could make some garden installations impossible, increase enclosure costs.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Follow BSI and BEIS fire safety consultations; specify fire-rated enclosures from the start; LFP chemistry already has strong safety profile.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'in-progress',
    residualScore: 4,
    triggerThreshold: 'BSI publishes new standards for residential battery installations or any UK battery fire incident',
    contingencyPlan: 'Upgrade enclosures to meet new standards; factor additional cost into future installations.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-REG-004',
    name: 'SEIS/EIS Excluded Trade Risk',
    category: 'regulatory',
    description: 'HMRC may determine that energy arbitrage / trading constitutes an "excluded trade" under SEIS/EIS rules, disqualifying RoseStack from SEIS/EIS relief for investors. This would significantly reduce the attractiveness of the investment to early-stage angels and seed investors who are relying on 50% SEIS income tax relief.',
    probability: 3,
    impact: 4,
    score: 12,
    rating: riskRating(12),
    mitigationStrategy: 'Obtain HMRC Advance Assurance before raising under SEIS/EIS. Structure the business around a service delivery model (ESA with homeowners, not energy trading) rather than a pure trading model. Engage specialist SEIS/EIS tax counsel (e.g. Osborne Clarke, Gateley) to review trading characterisation.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 5,
    triggerThreshold: 'HMRC issues any guidance on battery storage / arbitrage businesses and SEIS/EIS; or if similar company receives HMRC rejection',
    contingencyPlan: 'Restructure to VCT or EIS-only raise; pivot investor pitch to focus on assets and ESA cashflows rather than SEIS relief; consider EIS-qualifying asset leasing model instead.',
    lastReviewed: new Date('2026-04-02'),
  },
  {
    id: 'R-REG-005',
    name: 'FCA regulation of ESA',
    category: 'regulatory',
    description: 'FCA determines the Energy Services Agreement is a regulated credit agreement. Requires FCA authorisation — significant compliance cost and delay.',
    probability: 2,
    impact: 5,
    score: 10,
    rating: riskRating(10),
    mitigationStrategy: 'Structure ESA to avoid regulated credit characteristics; obtain legal opinion on FCA status; monitor FCA consultations on energy services.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 6,
    triggerThreshold: 'FCA issues guidance or consultation on energy service agreements or similar models',
    contingencyPlan: 'Restructure to pure lease model or apply for limited FCA authorisation.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-REG-005',
    name: 'MCS scheme changes',
    category: 'regulatory',
    description: 'MCS certification requirements tightened or costs increased. Increases per-installation compliance cost.',
    probability: 2,
    impact: 2,
    score: 4,
    rating: riskRating(4),
    mitigationStrategy: 'Maintain relationships with multiple MCS-certified installers; monitor MCS scheme consultations.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'not-started',
    residualScore: 3,
    triggerThreshold: 'MCS announces fee or requirement changes',
    contingencyPlan: 'Absorb additional cost; factor into future capex models.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-REG-006',
    name: 'G99 processing delays',
    category: 'regulatory',
    description: 'ENWL processing times extend beyond 12 weeks. Delays revenue start, increases working capital requirement.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: riskRating(9),
    mitigationStrategy: 'Submit G99 applications as early as possible; build 16-week processing time into financial models; maintain good ENWL relationship.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'in-progress',
    residualScore: 6,
    triggerThreshold: 'ENWL average G99 processing exceeds 12 weeks',
    contingencyPlan: 'Escalate through ENWL account manager; pre-fund additional working capital.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-REG-007',
    name: 'Consumer protection changes',
    category: 'regulatory',
    description: 'New consumer regulations affect long-term energy service contracts. Could require ESA restructuring or give homeowners easier exit rights.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Monitor CMA and BEIS consumer protection consultations; build fair terms into ESA from the start.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 4,
    triggerThreshold: 'CMA or BEIS consultation on long-term energy service contracts',
    contingencyPlan: 'Restructure ESA terms; may actually increase trust and reduce churn if terms are fairer.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-REG-008',
    name: 'P483 reversal or limitation',
    category: 'regulatory',
    description: 'Ofgem reverses or limits domestic battery participation in flexibility markets. Removes a key future revenue stream.',
    probability: 1,
    impact: 3,
    score: 3,
    rating: riskRating(3),
    mitigationStrategy: 'Do not include P483 flexibility revenue in base case; monitor Ofgem code modifications.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'implemented',
    residualScore: 2,
    triggerThreshold: 'Ofgem proposes modification to P483 or equivalent code change',
    contingencyPlan: 'Revenue impact minimal if not included in base case.',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- 4. Technology Risks ---
  {
    id: 'R-TEC-001',
    name: 'Accelerated battery degradation',
    category: 'technology',
    description: 'Batteries degrade faster than manufacturer specs (real-world vs lab conditions). Revenue declines faster, replacement needed earlier, model breaks.',
    probability: 2,
    impact: 4,
    score: 8,
    rating: riskRating(8),
    mitigationStrategy: 'Monitor Dave\'s system degradation monthly; compare against manufacturer curve; build 3% degradation into worst case model.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 6,
    triggerThreshold: 'Any system shows >3% degradation in first year or >2.5% average across portfolio',
    contingencyPlan: 'Trigger manufacturer warranty claims; adjust financial models; consider mid-life module replacement.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-TEC-002',
    name: 'Inverter failure rates',
    category: 'technology',
    description: 'Higher than expected inverter failure rate in the field. Maintenance cost increase, revenue downtime.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Select inverter with strong warranty (10+ years); stock spare parts; build maintenance reserve into operating costs.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'in-progress',
    residualScore: 4,
    triggerThreshold: 'Inverter failure rate exceeds 2% per annum across portfolio',
    contingencyPlan: 'Trigger warranty replacement; maintain emergency repair fund.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-TEC-003',
    name: 'Manufacturer bankruptcy',
    category: 'technology',
    description: 'Sigenergy (or chosen manufacturer) goes bust — no warranty, no spare parts, no software updates.',
    probability: 1,
    impact: 5,
    score: 5,
    rating: riskRating(5),
    mitigationStrategy: 'Monitor Sigenergy financial health; evaluate backup manufacturer options (GivEnergy, Tesla Powerwall); ensure software can run independently.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 4,
    triggerThreshold: 'Manufacturer credit rating downgrade or negative press about financial stability',
    contingencyPlan: 'Switch to alternative manufacturer for new installs; source third-party spare parts for existing fleet.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-TEC-004',
    name: 'Cybersecurity breach',
    category: 'technology',
    description: 'Battery management system or cloud platform hacked. Revenue loss during downtime, reputational damage, potential safety issue.',
    probability: 1,
    impact: 4,
    score: 4,
    rating: riskRating(4),
    mitigationStrategy: 'Implement network segmentation; regular firmware updates; cyber insurance; incident response plan.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 3,
    triggerThreshold: 'Any unauthorised access to battery management systems or any energy sector cyber incident',
    contingencyPlan: 'Isolate affected systems; manual override to safe state; insurance claim; customer notification.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-TEC-005',
    name: 'Software platform failure',
    category: 'technology',
    description: 'mySigen or Octopus Kraken platform outage prevents charge/discharge optimisation. Revenue loss during outage period.',
    probability: 3,
    impact: 2,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Monitor platform uptime; develop local fallback scheduling; maintain manual override capability.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 4,
    triggerThreshold: 'Platform outage exceeding 4 hours or more than 3 outages in a month',
    contingencyPlan: 'Switch to manual time-based charging schedule; claim compensation from platform provider.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-TEC-006',
    name: 'Technology leapfrog',
    category: 'technology',
    description: 'New battery technology (solid-state, sodium-ion) makes current LFP systems obsolete or uncompetitive. Existing portfolio locked into older tech at higher cost.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: riskRating(9),
    mitigationStrategy: 'Monitor battery tech developments; ensure ESA contracts allow for system upgrade paths; track sodium-ion progress.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 3,
    triggerThreshold: 'New chemistry achieves <$50/kWh at commercial scale with comparable cycle life',
    contingencyPlan: 'Existing LFP systems still generate revenue; transition new installs to better chemistry.',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- 5. Operational Risks ---
  {
    id: 'R-OPS-000',
    name: 'Single-property test dependency',
    category: 'operational',
    description: 'All backtesting, revenue projections, and financial modelling are based on a single reference property — The Beeches (192kWh/96kW, 3-phase, Burnley). This creates survivorship bias: if The Beeches is unrepresentatively favourable (large garden, good grid connection, high-consumption household), portfolio projections will overstate actual fleet performance.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: riskRating(9),
    mitigationStrategy: 'Model 3-5 representative properties covering the full spectrum of deployment scenarios: (1) The Beeches 192kWh/96kW 3-phase [existing], (2) Garden Standard 160kWh/40kW 3-phase, (3) Single-phase 54kWh/11.5kW, (4) Semi-detached terraced limited garden, (5) Constrained substation area. Run all financial projections against the full representative set and use the average, not just The Beeches.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 4,
    triggerThreshold: 'Any deviation >15% between The Beeches actuals and projected revenue in the first 6 months post-installation',
    contingencyPlan: 'Recalibrate financial models against actual fleet data once 3+ homes are live. Update SAVING_SESSIONS, REVENUE_MIX, and CAPACITY_RESERVE constants with real observed values.',
    lastReviewed: new Date('2026-04-02'),
  },
  {
    id: 'R-OPS-001',
    name: 'Installer capacity',
    category: 'operational',
    description: 'Can\'t find enough qualified MCS installers to hit deployment targets. Deployment schedule slips, revenue ramp delayed.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: riskRating(9),
    mitigationStrategy: 'Identify and pre-qualify 3+ MCS installers in Lancashire; offer volume commitments for priority scheduling.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'in-progress',
    residualScore: 6,
    triggerThreshold: 'Fewer than 2 qualified installers available or installation wait time exceeds 8 weeks',
    contingencyPlan: 'Recruit installers from wider northwest region; consider in-house installation team if volume justifies.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-OPS-002',
    name: 'Homeowner churn',
    category: 'operational',
    description: 'Homeowners want to exit ESA early (house sale, dissatisfaction, divorce). Revenue loss, asset recovery cost, potential legal disputes.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: riskRating(9),
    mitigationStrategy: 'Strong homeowner proposition (zero bills + £100/month); ESA transfer clause for house sales; excellent customer service.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 6,
    triggerThreshold: 'Churn rate exceeds 3% per annum or 2+ homeowners request exit in any quarter',
    contingencyPlan: 'Transfer ESA to new homeowner on house sale; recover and redeploy system if exit unavoidable.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-OPS-003',
    name: 'Theft or vandalism',
    category: 'operational',
    description: 'Battery system stolen or damaged. Insurance claim, revenue downtime, replacement cost.',
    probability: 1,
    impact: 3,
    score: 3,
    rating: riskRating(3),
    mitigationStrategy: 'Secure enclosures with tamper detection; GPS tracking; comprehensive insurance; garden placement reduces visibility.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'not-started',
    residualScore: 2,
    triggerThreshold: 'Any theft attempt or vandalism incident',
    contingencyPlan: 'Insurance claim; police report; replacement from stock.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-OPS-004',
    name: 'Property access issues',
    category: 'operational',
    description: 'Homeowner refuses access for maintenance or monitoring. System performance degrades, potential contract breach.',
    probability: 2,
    impact: 2,
    score: 4,
    rating: riskRating(4),
    mitigationStrategy: 'ESA includes clear access rights; remote monitoring reduces need for physical access; scheduled maintenance windows.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'implemented',
    residualScore: 2,
    triggerThreshold: 'Homeowner denies scheduled access twice in succession',
    contingencyPlan: 'Invoke ESA access clause; if persistent, consider contract termination and system recovery.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-OPS-005',
    name: 'Homeowner switches supplier',
    category: 'operational',
    description: 'Homeowner changes energy supplier without notifying RoseStack — new supplier may not support IOF or battery configuration. Revenue loss, system may stop optimising.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'ESA clause requiring notification before supplier switch; Letter of Authority for supplier changes; remote monitoring alerts.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 4,
    triggerThreshold: 'Revenue drop >20% from any home without scheduled reason',
    contingencyPlan: 'Contact homeowner; invoke ESA clause; assist with supplier switch back to compatible tariff.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-OPS-006',
    name: 'Key person risk',
    category: 'operational',
    description: 'Dave or Josh unable to continue (illness, other commitments). Business continuity threat — both founders employed full-time elsewhere.',
    probability: 2,
    impact: 4,
    score: 8,
    rating: riskRating(8),
    mitigationStrategy: 'Document all processes; cross-train on critical tasks; platform automates most operations; identify potential co-founders or senior hires.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 6,
    triggerThreshold: 'Either founder unable to commit >10 hours/week for more than 4 consecutive weeks',
    contingencyPlan: 'Platform runs autonomously for revenue collection; bring in interim management; consider strategic sale if permanent.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-OPS-007',
    name: 'Subcontractor failure',
    category: 'operational',
    description: 'Installation subcontractor goes bust or delivers poor quality. Delays, rectification costs, warranty disputes.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Pre-qualify multiple installers; retain performance bonds on larger contracts; staged payments.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'not-started',
    residualScore: 4,
    triggerThreshold: 'Any installer financial distress signals or quality defect rate >5%',
    contingencyPlan: 'Switch to backup installer; rectify defects under warranty; claim against bond if available.',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- 6. Financial Risks ---
  {
    id: 'R-FIN-001',
    name: 'Interest rate rise',
    category: 'financial',
    description: 'Base rate increases push up asset finance costs. Higher debt service, lower net margin per home.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: riskRating(9),
    mitigationStrategy: 'Lock in fixed-rate finance where possible; model sensitivity at base rate +2%; build interest rate headroom into DSCR.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 6,
    triggerThreshold: 'Base rate rises above 6% or finance cost exceeds 8%',
    contingencyPlan: 'Slow deployment pace to match available capital; renegotiate terms; consider equity raise.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-FIN-002',
    name: 'Growth Guarantee Scheme (GGS) withdrawal',
    category: 'financial',
    description: 'Government withdraws Growth Guarantee Scheme (GGS). First facility may not be possible without personal guarantee. Succession: EFG → CBILS (2020) → RLS (2021) → GGS (July 2024).',
    probability: 2,
    impact: 4,
    score: 8,
    rating: riskRating(8),
    mitigationStrategy: 'Secure GGS-backed facility before any announced changes; develop alternative funding routes (asset finance, crowdfunding).',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 4,
    triggerThreshold: 'Government announces GGS review or budget consultation mentioning scheme changes',
    contingencyPlan: 'Asset finance against battery fleet; revenue-based lending; equity investment.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-FIN-003',
    name: 'Lender covenant breach',
    category: 'financial',
    description: 'Portfolio DSCR drops below lender covenant threshold. Loan acceleration, forced asset sale, business failure.',
    probability: 1,
    impact: 5,
    score: 5,
    rating: riskRating(5),
    mitigationStrategy: 'Maintain DSCR above 1.5x in likely case; monthly monitoring with early warning; cash reserve equivalent to 3 months debt service.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 3,
    triggerThreshold: 'DSCR falls below 1.3x or shows downward trend for 3 consecutive months',
    contingencyPlan: 'Negotiate waiver with lender; inject founder capital; reduce homeowner payments temporarily.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-FIN-004',
    name: 'Currency risk',
    category: 'financial',
    description: 'Battery hardware priced in USD/CNY — sterling weakness increases capex. Higher per-home capital cost.',
    probability: 3,
    impact: 2,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Negotiate GBP pricing with UK distributors; bulk purchase when sterling is strong; forward contracts for large orders.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'not-started',
    residualScore: 4,
    triggerThreshold: 'GBP/USD falls below 1.15 or GBP/CNY falls below 8.5',
    contingencyPlan: 'Accept higher capex with longer payback; delay orders until FX improves.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-FIN-005',
    name: 'Insurance cost escalation',
    category: 'financial',
    description: 'Insurers increase premiums for residential battery systems (fire risk perception). Reduces net margin.',
    probability: 2,
    impact: 2,
    score: 4,
    rating: riskRating(4),
    mitigationStrategy: 'LFP chemistry has excellent safety record; maintain comprehensive safety documentation; shop multiple insurers.',
    mitigationOwner: 'Josh',
    mitigationStatus: 'not-started',
    residualScore: 3,
    triggerThreshold: 'Insurance premium exceeds £800/year per home or any UK battery fire incident',
    contingencyPlan: 'Self-insure for smaller claims; negotiate portfolio-level policy.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-FIN-006',
    name: 'Cash flow gap',
    category: 'financial',
    description: 'Revenue timing doesn\'t match debt service payments. Working capital crunch in early years.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: riskRating(9),
    mitigationStrategy: 'Detailed cash flow modelling with weekly granularity; maintain 3-month cash reserve; stagger installation schedule to match funding drawdowns.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 6,
    triggerThreshold: 'Cash reserve falls below 2 months of debt service',
    contingencyPlan: 'Delay next installation; draw on revolving credit facility; founder cash injection.',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- 7. Competitive Risks ---
  {
    id: 'R-CMP-001',
    name: 'Octopus self-deployment',
    category: 'competitive',
    description: 'Octopus Energy deploys its own battery fleet to homeowners. Direct competition with deeper pockets and tariff control.',
    probability: 2,
    impact: 5,
    score: 10,
    rating: riskRating(10),
    mitigationStrategy: 'Build local knowledge moat in Lancashire; establish relationships before Octopus scales; focus on 3-phase niche that Octopus may not prioritise.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 8,
    triggerThreshold: 'Octopus announces residential battery deployment service or acquires a deployer',
    contingencyPlan: 'Pivot to white-label operator for Octopus; or differentiate on homeowner proposition and local service quality.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-CMP-002',
    name: 'National player enters Lancashire',
    category: 'competitive',
    description: 'Social Energy, Moixa, or similar scales into East Lancashire. Competes for same 3-phase homes and substation capacity.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'First-mover advantage in constrained substations; build homeowner referral network; local brand recognition.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 4,
    triggerThreshold: 'Competitor battery installation spotted in East Lancashire or competitor listing in Piclo Flex for ENWL territory',
    contingencyPlan: 'Accelerate deployment in priority substations; differentiate on homeowner proposition.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-CMP-003',
    name: 'Installer disintermediation',
    category: 'competitive',
    description: 'Heatable or other installers copy the model and cut out RoseStack. Lose control of the value chain.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Build technology and optimisation moat; lock in installers with volume commitments; platform value exceeds simple installation.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 4,
    triggerThreshold: 'Any MCS installer in Lancashire launches lease or ESA model for batteries',
    contingencyPlan: 'Differentiate on platform, data, and optimisation; offer installer partnership model.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-CMP-004',
    name: 'Homeowner self-install',
    category: 'competitive',
    description: 'Battery costs fall enough that homeowners buy their own systems. Reduces addressable market for lease/ESA model.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: riskRating(9),
    mitigationStrategy: 'Emphasise zero-capex advantage; target homeowners who cannot or prefer not to spend £48K; offer value-add services self-installers cannot access.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 6,
    triggerThreshold: 'Residential battery installed cost drops below £20K for 100kWh+ system',
    contingencyPlan: 'Pivot to management-only SaaS model for homeowner-owned systems; charge optimisation fee.',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'R-CMP-005',
    name: 'Utility company response',
    category: 'competitive',
    description: 'E.ON, British Gas, or EDF launch competing residential battery schemes. Well-funded competition with existing customer bases.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: riskRating(6),
    mitigationStrategy: 'Move fast to build local portfolio before national players scale; leverage local relationships and knowledge.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 4,
    triggerThreshold: 'Major utility announces residential battery scheme in north of England',
    contingencyPlan: 'Position as local specialist; potential acquisition target for utility seeking rapid local scale.',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- New risks from March 2026 review ---
  {
    id: 'R-NEW-001',
    name: 'IOF tariff signup suspension',
    category: 'tariff',
    description: 'Octopus has paused new IOF/Flux signups March 2026.',
    probability: 5,
    impact: 4,
    score: 20,
    rating: riskRating(20),
    mitigationStrategy: 'Monitor daily, prepare Agile fallback strategy, join waitlist.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 12,
    triggerThreshold: 'IOF/Flux signups remain closed for more than 30 days',
    contingencyPlan: 'Default new deployments to Agile tariff with automated optimisation.',
    lastReviewed: new Date('2026-03-25'),
  },
  {
    id: 'R-NEW-002',
    name: 'Lithium-ion battery safety legislation',
    category: 'regulatory',
    description: 'Product Regulation & Metrology Bill and Lithium-ion Battery Safety Bill in Parliament.',
    probability: 4,
    impact: 3,
    score: 12,
    rating: riskRating(12),
    mitigationStrategy: 'Monitor legislative progress, ensure PAS 63100 compliance, design for future-proofing.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 6,
    triggerThreshold: 'Either Bill passes committee stage or new PAS requirements published',
    contingencyPlan: 'Ensure all installations exceed anticipated safety standards; budget for retrofit compliance.',
    lastReviewed: new Date('2026-03-25'),
  },
  {
    id: 'R-NEW-003',
    name: 'Regional battery price premium',
    category: 'financial',
    description: 'UK/European battery prices 56-227% above Chinese domestic.',
    probability: 4,
    impact: 3,
    score: 12,
    rating: riskRating(12),
    mitigationStrategy: 'Explore direct manufacturer relationships, volume purchasing.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 8,
    triggerThreshold: 'UK premium exceeds 200% vs Chinese domestic for equivalent spec',
    contingencyPlan: 'Source directly from Chinese manufacturers via UK import agent.',
    lastReviewed: new Date('2026-03-25'),
  },
  {
    id: 'R-NEW-004',
    name: 'Geopolitical energy price volatility',
    category: 'energy-market',
    description: 'Middle East conflict driving unpredictable wholesale conditions.',
    probability: 4,
    impact: 3,
    score: 12,
    rating: riskRating(12),
    mitigationStrategy: 'Diversify revenue streams, don\'t depend on single tariff.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'in-progress',
    residualScore: 8,
    triggerThreshold: 'Wholesale price volatility exceeds 50% month-on-month for 3 consecutive months',
    contingencyPlan: 'Rebalance portfolio across tariff types; increase flexibility market participation.',
    lastReviewed: new Date('2026-03-25'),
  },
  {
    id: 'R-REG-PAS63100-BEECHES',
    name: 'PAS 63100 capacity exceedance — The Beeches',
    category: 'regulatory',
    description:
      'The Beeches is a 192kWh installation. PAS 63100:2024 limits domestic external BESS to 80kWh maximum. This system is 112kWh over the limit. Resolution route not yet confirmed. Risk of: (1) insurance invalidation if insurer requires PAS 63100 compliance; (2) potential enforcement action by Lancashire Fire & Rescue; (3) reputational damage if fire incident occurs at an out-of-compliance installation.',
    probability: 4,
    impact: 4,
    score: 16,
    rating: riskRating(16),
    mitigationStrategy:
      'Confirm resolution route before any further >80kWh deployments. Three routes available: (A) Multiple enclosures each <80kWh with required separation; (B) Site-specific fire risk assessment + Lancashire Fire & Rescue non-domestic classification; (C) Reduce system size to ≤80kWh. Engage insurer and Lancashire Fire & Rescue immediately.',
    mitigationOwner: 'Dave',
    mitigationStatus: 'not-started',
    residualScore: 6,
    triggerThreshold:
      'Any insurance renewal, fire inspection, or new MCS audit that requires PAS 63100 sign-off',
    contingencyPlan:
      'If no resolution route is confirmed: (1) pause all >80kWh new installations; (2) engage specialist fire safety consultant for site-specific assessment of The Beeches; (3) notify insurer proactively and confirm coverage remains valid.',
    lastReviewed: new Date('2026-04-03'),
  },
];

// ============================================================
// OPPORTUNITIES
// ============================================================

export const SEEDED_OPPORTUNITIES: OpportunityItem[] = [
  // --- 1. Hardware Cost Reduction Opportunities ---
  {
    id: 'O-HWC-001',
    name: 'LFP battery price decline',
    category: 'hardware-cost',
    description: 'Global LFP cell prices continuing to fall (down ~70% since 2020). Every 10% capex reduction = faster payback, higher ROI, more homes fundable per £.',
    probability: 4,
    impact: 4,
    score: 16,
    rating: opportunityRating(16),
    captureStrategy: 'Monitor BloombergNEF and battery price indices; renegotiate hardware pricing annually; time bulk purchases to price dips.',
    captureOwner: 'Josh',
    captureStatus: 'researching',
    expectedValue: 50000,
    triggerThreshold: 'LFP cell price drops below $80/kWh or 204kWh system price drops below £40K',
    dependencies: ['Volume purchasing agreement with manufacturer'],
    investmentRequired: 'No additional investment — natural market trend',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-HWC-002',
    name: 'Sodium-ion commercialisation',
    category: 'hardware-cost',
    description: 'CATL Naxtra and others bring Na-ion to market at 30-40% below LFP. 204kWh system could drop from ~£48K to ~£30K — payback under 12 months.',
    probability: 4,
    impact: 5,
    score: 20,
    rating: opportunityRating(20),
    captureStrategy: 'Track CATL Naxtra UK availability timeline; evaluate Na-ion cycle life and cold-weather performance for Lancashire; test pilot unit when available.',
    captureOwner: 'Dave',
    captureStatus: 'researching',
    expectedValue: 90000,
    triggerThreshold: 'Na-ion batteries available in UK market with >6000 cycle life and comparable energy density',
    dependencies: ['UK distribution channel for Na-ion batteries', 'MCS certification for Na-ion systems'],
    investmentRequired: 'Pilot unit purchase for testing (~£5K-10K)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-HWC-003',
    name: 'Inverter commoditisation',
    category: 'hardware-cost',
    description: 'More 3-phase hybrid inverters entering UK market drives prices down. Reduces per-home capex, widens supplier options.',
    probability: 4,
    impact: 3,
    score: 12,
    rating: opportunityRating(12),
    captureStrategy: 'Monitor new inverter entrants (Deye, Sofar, Sungrow); evaluate compatibility with battery systems; negotiate competitive pricing.',
    captureOwner: 'Josh',
    captureStatus: 'researching',
    expectedValue: 20000,
    triggerThreshold: '3+ MCS-approved 3-phase hybrid inverters available below £3K',
    dependencies: ['MCS approval for new inverter models'],
    investmentRequired: 'None beyond evaluation time',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-HWC-004',
    name: 'Second-life EV batteries',
    category: 'hardware-cost',
    description: 'Retired EV batteries (70-80% remaining capacity) become available cheaply. Potential ultra-low-cost systems for flexibility-only deployments.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: opportunityRating(6),
    captureStrategy: 'Monitor EV battery retirement volumes from UK vehicle fleet; evaluate integration with existing inverter platform.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 15000,
    triggerThreshold: 'Second-life EV battery packs available below £30/kWh with verified capacity',
    dependencies: ['Integration solution for EV battery packs', 'Safety certification'],
    investmentRequired: 'R&D for integration solution (~£10K-20K)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-HWC-005',
    name: 'Chinese manufacturer direct',
    category: 'hardware-cost',
    description: 'Bypass UK distributors and import battery/inverter direct from manufacturers. 20-40% cost reduction on hardware at volume.',
    probability: 3,
    impact: 4,
    score: 12,
    rating: opportunityRating(12),
    captureStrategy: 'Attend Canton Fair and RE+ China; establish direct relationships with CATL, BYD, Sigenergy factories; negotiate direct supply agreements at 50+ unit volumes.',
    captureOwner: 'Josh',
    captureStatus: 'not-started',
    expectedValue: 40000,
    triggerThreshold: 'Portfolio reaches 20+ homes or committed orders exceed 30 units',
    dependencies: ['Import logistics and customs clearance', 'UK type approval for direct imports'],
    investmentRequired: 'Travel costs (~£3K) plus minimum order quantity deposit',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-HWC-006',
    name: 'Volume purchasing power',
    category: 'hardware-cost',
    description: 'As portfolio grows, negotiate better hardware pricing. 50+ systems = significant leverage with Sigenergy or alternatives.',
    probability: 4,
    impact: 3,
    score: 12,
    rating: opportunityRating(12),
    captureStrategy: 'Track cumulative purchase volume; approach manufacturers at 20, 50, 100 unit milestones; negotiate volume discount schedules.',
    captureOwner: 'Josh',
    captureStatus: 'not-started',
    expectedValue: 25000,
    triggerThreshold: 'Cumulative orders exceed 20 units or annual run rate exceeds 15 units',
    dependencies: ['Secured funding for bulk purchasing', 'Storage facility for advance orders'],
    investmentRequired: 'Working capital for advance purchasing',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- 2. Revenue Enhancement Opportunities ---
  {
    id: 'O-REV-001',
    name: 'Additional Saving Sessions',
    category: 'revenue-enhancement',
    description: 'ESO increases number of Saving Sessions per year (currently ~25). Each additional session = ~£150-700 per home depending on rate and capacity.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: opportunityRating(9),
    captureStrategy: 'Ensure all homes registered for DFS; automated participation via smart scheduling; monitor ESO announcements on DFS expansion.',
    captureOwner: 'Dave',
    captureStatus: 'in-progress',
    expectedValue: 30000,
    triggerThreshold: 'ESO announces increased DFS events or expanded geographic coverage',
    dependencies: ['Automated DFS participation system'],
    investmentRequired: 'None beyond platform development',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-REV-002',
    name: 'Saving Sessions rate increase',
    category: 'revenue-enhancement',
    description: 'ESO increases per-kWh payment rate for DFS events. Direct revenue uplift across entire portfolio.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: opportunityRating(9),
    captureStrategy: 'Automatically participate in all sessions; optimise battery state of charge before sessions to maximise discharge.',
    captureOwner: 'Dave',
    captureStatus: 'in-progress',
    expectedValue: 20000,
    triggerThreshold: 'Average DFS rate exceeds £4.00/kWh',
    dependencies: [],
    investmentRequired: 'None',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-REV-003',
    name: 'IOF rate improvement',
    category: 'revenue-enhancement',
    description: 'Octopus widens the spread as grid stress increases. Direct revenue increase — model 10%, 20% spread widening.',
    probability: 2,
    impact: 4,
    score: 8,
    rating: opportunityRating(8),
    captureStrategy: 'Monitor IOF rate announcements; model revenue at multiple spread scenarios; maintain good relationship with Octopus commercial team.',
    captureOwner: 'Dave',
    captureStatus: 'researching',
    expectedValue: 35000,
    triggerThreshold: 'IOF spread widens by >5% or Octopus announces rate review',
    dependencies: [],
    investmentRequired: 'None',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-REV-004',
    name: 'New premium tariffs',
    category: 'revenue-enhancement',
    description: 'Octopus or competitors launch new battery-optimised tariffs with better spreads. Potential to switch portfolio to higher-revenue tariff.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: opportunityRating(9),
    captureStrategy: 'Monitor all supplier tariff launches; evaluate new tariffs against current IOF revenue; rapid switching capability.',
    captureOwner: 'Dave',
    captureStatus: 'researching',
    expectedValue: 25000,
    triggerThreshold: 'New tariff offers >10% better revenue than current IOF',
    dependencies: ['ESA flexibility to switch tariffs'],
    investmentRequired: 'None',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-REV-005',
    name: 'Triple cycling',
    category: 'revenue-enhancement',
    description: 'Battery technology improvements allow 3 cycles per day instead of 2. Up to 50% revenue increase per home from same hardware.',
    probability: 2,
    impact: 5,
    score: 10,
    rating: opportunityRating(10),
    captureStrategy: 'Monitor battery cycle life improvements; evaluate feasibility of 3 daily cycles on current hardware; test degradation impact.',
    captureOwner: 'Dave',
    captureStatus: 'researching',
    expectedValue: 80000,
    triggerThreshold: 'Battery manufacturer warranties extended to 10000+ cycles or tariff structure creates 3 clear arbitrage windows daily',
    dependencies: ['Battery chemistry that supports high cycle count without excessive degradation'],
    investmentRequired: 'Testing on pilot system (~£0)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-REV-006',
    name: 'Seasonal optimisation',
    category: 'revenue-enhancement',
    description: 'Exploit winter/summer rate differentials more aggressively. Higher revenue in winter when spreads are typically wider.',
    probability: 4,
    impact: 2,
    score: 8,
    rating: opportunityRating(8),
    captureStrategy: 'Implement seasonal scheduling algorithms; adjust charge/discharge profiles based on forecast prices.',
    captureOwner: 'Dave',
    captureStatus: 'in-progress',
    expectedValue: 10000,
    triggerThreshold: 'Winter/summer spread differential exceeds 30%',
    dependencies: ['Advanced scheduling algorithm'],
    investmentRequired: 'Development time only',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-REV-007',
    name: 'Stacking Cosy + IOF',
    category: 'revenue-enhancement',
    description: 'Homes with heat pumps qualify for Octopus Cosy tariff windows alongside IOF. Additional cheap-rate charging windows = more arbitrage cycles.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: opportunityRating(6),
    captureStrategy: 'Identify homes with heat pumps; evaluate Cosy + IOF compatibility; model additional revenue from stacked tariff windows.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 15000,
    triggerThreshold: 'Octopus confirms Cosy and IOF can be stacked or portfolio includes 5+ heat pump homes',
    dependencies: ['Heat pump installed at RoseStack home', 'Octopus Cosy tariff compatibility with IOF'],
    investmentRequired: 'None',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- 3. Grid & Flexibility Market Opportunities ---
  {
    id: 'O-GRD-001',
    name: 'ENWL flexibility expansion',
    category: 'grid-flexibility',
    description: 'ENWL expands flexibility procurement as grid stress grows with EV adoption. More tender opportunities, higher prices per kW in constrained areas.',
    probability: 5,
    impact: 4,
    score: 20,
    rating: opportunityRating(20),
    captureStrategy: 'Register all homes on Piclo Flex; attend ENWL stakeholder events; position as preferred flexibility provider in East Lancashire.',
    captureOwner: 'Dave',
    captureStatus: 'in-progress',
    expectedValue: 60000,
    triggerThreshold: 'ENWL publishes new flexibility tenders in East Lancashire or expands procurement budget',
    dependencies: ['Portfolio of 10+ homes in constrained substation areas'],
    investmentRequired: 'None beyond Piclo registration',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-GRD-002',
    name: 'P483 full implementation',
    category: 'grid-flexibility',
    description: 'Full domestic battery participation in flexibility markets beds in. Unlocks £500-2,000/yr per home from flexibility alone.',
    probability: 3,
    impact: 4,
    score: 12,
    rating: opportunityRating(12),
    captureStrategy: 'Monitor P483 implementation timeline; prepare technical capability for flexibility market participation; engage with aggregators.',
    captureOwner: 'Dave',
    captureStatus: 'researching',
    expectedValue: 50000,
    triggerThreshold: 'P483 implementation date confirmed or domestic batteries begin participating in BM',
    dependencies: ['P483 code change implementation', 'Aggregator partnership'],
    investmentRequired: 'None beyond platform integration',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-GRD-003',
    name: 'Capacity Market access',
    category: 'grid-flexibility',
    description: 'Portfolio reaches minimum threshold for Capacity Market participation. £20-40/kW/year — potentially £4,000-8,000/yr for a 204kWh system.',
    probability: 2,
    impact: 4,
    score: 8,
    rating: opportunityRating(8),
    captureStrategy: 'Track CM auction requirements; aggregate portfolio capacity; apply through licensed aggregator when threshold met.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 40000,
    triggerThreshold: 'Portfolio aggregate capacity exceeds CM minimum threshold (currently 2MW)',
    dependencies: ['Portfolio scale of ~40+ homes', 'Aggregator agreement'],
    investmentRequired: 'Aggregator fees',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-GRD-004',
    name: 'Balancing Mechanism access',
    category: 'grid-flexibility',
    description: 'Aggregators open BM participation to smaller battery portfolios. Highest-value grid service — £100+/MWh during system stress events.',
    probability: 2,
    impact: 4,
    score: 8,
    rating: opportunityRating(8),
    captureStrategy: 'Monitor aggregator offerings for small-scale BM participation; evaluate revenue potential vs complexity.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 30000,
    triggerThreshold: 'Aggregator offers BM access at portfolio scale below 5MW',
    dependencies: ['Aggregator BM access platform', 'Sub-second response capability'],
    investmentRequired: 'Aggregator fees and potential metering upgrades',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-GRD-005',
    name: 'BiTraDER secondary trading',
    category: 'grid-flexibility',
    description: 'ENWL\'s secondary flexibility trading platform goes live in Lancashire. Additional revenue stream from peer-to-peer flexibility trading.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: opportunityRating(9),
    captureStrategy: 'Register for BiTraDER pilot; understand trading mechanics; develop automated bidding strategy.',
    captureOwner: 'Dave',
    captureStatus: 'researching',
    expectedValue: 20000,
    triggerThreshold: 'BiTraDER platform opens for Lancashire residential flexibility providers',
    dependencies: ['BiTraDER platform launch', 'Flexibility aggregation capability'],
    investmentRequired: 'Platform integration development',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-GRD-006',
    name: 'V2G integration',
    category: 'grid-flexibility',
    description: 'Vehicle-to-Grid matures — homes with EVs add car battery to the arbitrage pool. 40-80kWh additional capacity per home at zero hardware cost.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: opportunityRating(6),
    captureStrategy: 'Monitor V2G charger availability and compatibility; evaluate integration with existing battery system; target homes with EVs.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 25000,
    triggerThreshold: 'V2G chargers available below £1K and compatible with 3-phase Sigenergy systems',
    dependencies: ['V2G-capable EV chargers', 'Vehicle manufacturer support'],
    investmentRequired: 'V2G charger per home (~£500-1500)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-GRD-007',
    name: 'Grid constraint worsening',
    category: 'grid-flexibility',
    description: 'More EVs and heat pumps overload local substations. Increases DNO willingness to pay for flexibility = higher tender prices.',
    probability: 4,
    impact: 3,
    score: 12,
    rating: opportunityRating(12),
    captureStrategy: 'Map constrained substations in East Lancashire; prioritise deployment near constraint points; build ENWL relationship.',
    captureOwner: 'Dave',
    captureStatus: 'in-progress',
    expectedValue: 35000,
    triggerThreshold: 'ENWL reports additional constrained substations in East Lancashire or increases flex procurement prices',
    dependencies: ['ENWL constraint data access'],
    investmentRequired: 'None',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- 4. Policy & Regulatory Tailwinds ---
  {
    id: 'O-POL-001',
    name: 'Government battery storage incentive',
    category: 'policy-tailwind',
    description: 'UK government introduces grant or tax relief for residential battery storage. Reduces capex, potentially makes 1-phase homes viable.',
    probability: 2,
    impact: 5,
    score: 10,
    rating: opportunityRating(10),
    captureStrategy: 'Monitor BEIS and Treasury announcements; prepare application infrastructure for rapid uptake; model impact on business case.',
    captureOwner: 'Dave',
    captureStatus: 'researching',
    expectedValue: 100000,
    triggerThreshold: 'Government announces battery storage incentive consultation or budget inclusion',
    dependencies: ['Government policy decision'],
    investmentRequired: 'None',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-POL-002',
    name: 'Mandated new-build batteries',
    category: 'policy-tailwind',
    description: 'Building regulations require battery storage in new homes. Massive new market for RoseStack deployment or SaaS licensing.',
    probability: 2,
    impact: 5,
    score: 10,
    rating: opportunityRating(10),
    captureStrategy: 'Monitor building regulations consultations; position RoseStack as solution for developer compliance; develop developer partnership model.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 200000,
    triggerThreshold: 'Building regulations consultation includes battery storage mandate',
    dependencies: ['Building regulation change'],
    investmentRequired: 'Developer partnership development',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-POL-003',
    name: 'Carbon border adjustments',
    category: 'policy-tailwind',
    description: 'Carbon pricing makes fossil fuel electricity more expensive. Widens the renewable/storage arbitrage spread.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: opportunityRating(9),
    captureStrategy: 'No specific action needed — benefit flows through automatically via wider tariff spreads.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 15000,
    triggerThreshold: 'UK CBAM implementation or carbon price exceeds £100/tonne',
    dependencies: [],
    investmentRequired: 'None',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-POL-004',
    name: 'Local authority partnerships',
    category: 'policy-tailwind',
    description: 'Councils seeking to meet net zero targets fund community battery schemes. Bulk deployment contracts with guaranteed revenue.',
    probability: 3,
    impact: 4,
    score: 12,
    rating: opportunityRating(12),
    captureStrategy: 'Approach Blackburn, Burnley, and Ribble Valley councils; present at council net zero strategy meetings; propose community battery pilot.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 75000,
    triggerThreshold: 'Any Lancashire council publishes net zero action plan mentioning battery storage',
    dependencies: ['Proven portfolio performance data', 'Council engagement strategy'],
    investmentRequired: 'Time for council engagement',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-POL-005',
    name: 'Green mortgage products',
    category: 'policy-tailwind',
    description: 'Lenders offer better rates for homes with battery storage. Increases homeowner willingness to host RoseStack systems.',
    probability: 3,
    impact: 2,
    score: 6,
    rating: opportunityRating(6),
    captureStrategy: 'Monitor green mortgage product launches; partner with green mortgage providers; include in homeowner proposition.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 10000,
    triggerThreshold: 'Major UK lender launches green mortgage product that covers battery storage',
    dependencies: [],
    investmentRequired: 'None',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-POL-006',
    name: 'BUS grant expansion',
    category: 'policy-tailwind',
    description: 'Boiler Upgrade Scheme expanded to include battery storage alongside heat pumps. Reduces homeowner/deployer capex.',
    probability: 2,
    impact: 3,
    score: 6,
    rating: opportunityRating(6),
    captureStrategy: 'Monitor BUS scheme consultations; prepare application process for rapid uptake if expanded.',
    captureOwner: 'Josh',
    captureStatus: 'not-started',
    expectedValue: 30000,
    triggerThreshold: 'BEIS announces BUS expansion consultation or includes battery storage',
    dependencies: ['Government policy decision'],
    investmentRequired: 'None',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- 5. Business Model Opportunities ---
  {
    id: 'O-BIZ-001',
    name: 'SaaS licensing',
    category: 'business-model',
    description: 'License the RoseStack platform to other battery deployers nationally. Recurring revenue with near-zero marginal cost.',
    probability: 3,
    impact: 5,
    score: 15,
    rating: opportunityRating(15),
    captureStrategy: 'Build platform with multi-tenant architecture; document APIs; identify potential licensees once portfolio proves concept.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 150000,
    triggerThreshold: 'Portfolio exceeds 30 homes with 12+ months performance data or inbound inquiry from another deployer',
    dependencies: ['Proven portfolio performance', 'Multi-tenant platform architecture'],
    investmentRequired: 'Platform development for multi-tenancy (~£20K-50K)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-BIZ-002',
    name: 'White-label hardware',
    category: 'business-model',
    description: 'Develop RoseStack-branded battery modules using Chinese OEM manufacturing. Control the supply chain, higher margins, brand value.',
    probability: 2,
    impact: 4,
    score: 8,
    rating: opportunityRating(8),
    captureStrategy: 'Research OEM manufacturing options; evaluate minimum order quantities; assess brand value vs cost at target volumes.',
    captureOwner: 'Josh',
    captureStatus: 'not-started',
    expectedValue: 60000,
    triggerThreshold: 'Portfolio exceeds 50 homes or annual deployment exceeds 20 systems',
    dependencies: ['Volume to justify minimum order', 'UK type approval for white-label product'],
    investmentRequired: 'Product development and tooling (~£50K-100K)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-BIZ-003',
    name: 'Installer network',
    category: 'business-model',
    description: 'Build a network of certified RoseStack installers across the northwest. Scale deployments without hiring, earn margin on installation.',
    probability: 4,
    impact: 3,
    score: 12,
    rating: opportunityRating(12),
    captureStrategy: 'Identify and pre-qualify MCS installers; develop RoseStack installer certification process; offer volume guarantees.',
    captureOwner: 'Josh',
    captureStatus: 'not-started',
    expectedValue: 30000,
    triggerThreshold: 'Deployment rate exceeds 2 installations per month',
    dependencies: ['Proven installation methodology', 'Quality standards documentation'],
    investmentRequired: 'Certification programme development (~£5K)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-BIZ-004',
    name: 'Data monetisation',
    category: 'business-model',
    description: 'Anonymised portfolio performance data valuable to DNOs, energy traders, researchers. Revenue from data that\'s already being collected.',
    probability: 3,
    impact: 2,
    score: 6,
    rating: opportunityRating(6),
    captureStrategy: 'Build data anonymisation pipeline; approach ENWL, universities, and energy researchers with data proposition.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 15000,
    triggerThreshold: 'Portfolio exceeds 20 homes with 6+ months data',
    dependencies: ['Data anonymisation pipeline', 'GDPR compliance review'],
    investmentRequired: 'Data platform development (~£5K)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-BIZ-005',
    name: 'Franchise model',
    category: 'business-model',
    description: 'License the entire RoseStack model to operators in other DNO regions. National scale without national overhead.',
    probability: 2,
    impact: 5,
    score: 10,
    rating: opportunityRating(10),
    captureStrategy: 'Document the complete RoseStack operating model; develop franchise package; target 2-3 pilot regions.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 100000,
    triggerThreshold: 'Lancashire operation profitable for 12+ months with proven, documented processes',
    dependencies: ['Profitable Lancashire operation', 'Documented operating model', 'Legal franchise agreement'],
    investmentRequired: 'Franchise development (~£30K-50K)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-BIZ-006',
    name: 'Community energy schemes',
    category: 'business-model',
    description: 'Structure community-owned battery projects using cooperative model. Access community energy funding, goodwill, and different customer segments.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: opportunityRating(9),
    captureStrategy: 'Research community energy funding sources (e.g. Power to Change); identify suitable communities; develop co-op structure.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 40000,
    triggerThreshold: 'Community energy funding available for battery storage or inbound community inquiry',
    dependencies: ['Community energy legal structure', 'Suitable community partner'],
    investmentRequired: 'Legal structuring (~£10K)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-BIZ-007',
    name: 'Commercial/industrial pivot',
    category: 'business-model',
    description: 'Adapt the model for businesses, farms, schools with larger systems. Higher per-site revenue (£8-15K/yr), simpler sales process (one decision-maker).',
    probability: 3,
    impact: 4,
    score: 12,
    rating: opportunityRating(12),
    captureStrategy: 'Identify target commercial sites in East Lancashire; model revenue for larger systems; develop commercial proposition.',
    captureOwner: 'Dave',
    captureStatus: 'researching',
    expectedValue: 70000,
    triggerThreshold: 'Inbound inquiry from commercial site or completion of first 10 domestic installations',
    dependencies: ['Commercial system design and costing', 'Larger inverter options evaluated'],
    investmentRequired: 'Commercial system pilot (~£30K-50K)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-BIZ-008',
    name: 'EV charging integration',
    category: 'business-model',
    description: 'Add EV charging to RoseStack homes — charge from battery at off-peak rates. Additional revenue stream + makes the proposition more attractive to homeowners.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: opportunityRating(9),
    captureStrategy: 'Evaluate EV charger integration with Sigenergy system; model additional revenue from EV charging arbitrage.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 20000,
    triggerThreshold: 'EV charger compatible with Sigenergy available below £1K or 30%+ of target homes have EVs',
    dependencies: ['Compatible EV charger', 'Battery-to-EV charging capability'],
    investmentRequired: 'EV charger per home (~£500-1000)',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- 6. Competitive Advantage Opportunities ---
  {
    id: 'O-CMP-001',
    name: 'First-mover substation lock-in',
    category: 'competitive-advantage',
    description: 'Saturate constrained substations before competitors arrive. Monopoly position in the highest-value grid areas.',
    probability: 4,
    impact: 5,
    score: 20,
    rating: opportunityRating(20),
    captureStrategy: 'Map all constrained substations in East Lancashire; prioritise deployment in highest-value areas; register flexibility capacity early.',
    captureOwner: 'Dave',
    captureStatus: 'in-progress',
    expectedValue: 100000,
    triggerThreshold: 'First RoseStack home live on constrained substation or competitor activity detected',
    dependencies: ['ENWL constraint data', 'Homes identified near constrained substations'],
    investmentRequired: 'Standard deployment capex — prioritisation rather than additional investment',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-CMP-002',
    name: 'Real-world performance data',
    category: 'competitive-advantage',
    description: '12+ months of auditable data from Dave\'s own system. Competitive moat — competitors can only offer projections, we have proof.',
    probability: 5,
    impact: 4,
    score: 20,
    rating: opportunityRating(20),
    captureStrategy: 'Meticulously record all performance data; publish performance reports; use in investor and homeowner conversations.',
    captureOwner: 'Dave',
    captureStatus: 'in-progress',
    expectedValue: 50000,
    triggerThreshold: '6 months of continuous performance data collected',
    dependencies: ['Dave\'s system installed and live'],
    investmentRequired: 'None — data collection is automatic',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-CMP-003',
    name: 'Homeowner referral network',
    category: 'competitive-advantage',
    description: 'Each installed home generates referrals from neighbours. Organic growth engine with near-zero acquisition cost.',
    probability: 4,
    impact: 3,
    score: 12,
    rating: opportunityRating(12),
    captureStrategy: 'Implement referral incentive programme; encourage homeowners to share experience; track referral conversion rates.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 20000,
    triggerThreshold: 'First organic referral from installed homeowner',
    dependencies: ['Happy homeowner with live system'],
    investmentRequired: 'Referral incentive (~£500 per referral conversion)',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-CMP-004',
    name: 'ENWL relationship',
    category: 'competitive-advantage',
    description: 'Become ENWL\'s preferred residential flexibility partner in East Lancashire. Priority access to flexibility tenders, influence on future procurement design.',
    probability: 3,
    impact: 4,
    score: 12,
    rating: opportunityRating(12),
    captureStrategy: 'Attend ENWL stakeholder events; deliver excellent flexibility performance; propose pilot projects.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 50000,
    triggerThreshold: 'ENWL stakeholder event invitation or direct ENWL contact established',
    dependencies: ['Registered flexibility portfolio on Piclo Flex'],
    investmentRequired: 'Time for relationship building',
    lastReviewed: new Date('2026-03-01'),
  },
  {
    id: 'O-CMP-005',
    name: 'Installer loyalty',
    category: 'competitive-advantage',
    description: 'Lock in best MCS installers with volume guarantees before competitors. Capacity moat — competitors can\'t deploy if installers are committed to us.',
    probability: 3,
    impact: 3,
    score: 9,
    rating: opportunityRating(9),
    captureStrategy: 'Identify top 3 MCS installers in Lancashire; offer volume guarantee agreements; build strong working relationships.',
    captureOwner: 'Josh',
    captureStatus: 'not-started',
    expectedValue: 20000,
    triggerThreshold: 'First installer volume commitment signed or 5+ installations completed with preferred installer',
    dependencies: ['Funding secured for deployment pipeline'],
    investmentRequired: 'Volume commitment (use-or-pay clause)',
    lastReviewed: new Date('2026-03-01'),
  },

  // --- New opportunities from March 2026 review ---
  {
    id: 'O-NEW-001',
    name: 'ENWL reduced flexibility minimum',
    category: 'grid-flexibility',
    description: 'Lowered from 50kW to 10kW, enabling individual home participation.',
    probability: 5,
    impact: 4,
    score: 20,
    rating: opportunityRating(20),
    captureStrategy: 'Register with ENWL as flexibility provider.',
    captureOwner: 'Dave',
    captureStatus: 'not-started',
    expectedValue: 40000,
    triggerThreshold: 'ENWL confirms 10kW minimum threshold is active for new registrations',
    dependencies: ['Flexibility provider registration with ENWL'],
    investmentRequired: 'Registration and compliance costs only',
    lastReviewed: new Date('2026-03-25'),
  },
  {
    id: 'O-NEW-002',
    name: 'Warm Homes Plan battery inclusion',
    category: 'policy-tailwind',
    description: '£15B government programme now includes battery storage.',
    probability: 4,
    impact: 4,
    score: 16,
    rating: opportunityRating(16),
    captureStrategy: 'Apply for Warm Homes funding for social housing deployments.',
    captureOwner: 'Josh',
    captureStatus: 'not-started',
    expectedValue: 100000,
    triggerThreshold: 'Warm Homes Plan application window opens for battery storage projects',
    dependencies: ['Social housing partnership', 'Warm Homes Plan eligibility confirmed'],
    investmentRequired: 'Application preparation and partnership development',
    lastReviewed: new Date('2026-03-25'),
  },
  {
    id: 'O-NEW-003',
    name: 'Stationary storage cost collapse',
    category: 'hardware-cost',
    description: 'Battery pack prices dropped 45% in 2025 to $70/kWh.',
    probability: 5,
    impact: 4,
    score: 20,
    rating: opportunityRating(20),
    captureStrategy: 'Renegotiate hardware pricing, model accelerated deployment.',
    captureOwner: 'Dave',
    captureStatus: 'researching',
    expectedValue: 80000,
    triggerThreshold: 'Battery pack prices confirmed below $70/kWh for UK-available systems',
    dependencies: ['Updated supplier quotes', 'Revised financial model'],
    investmentRequired: 'None — reduces existing costs',
    lastReviewed: new Date('2026-03-25'),
  },
  {
    id: 'O-NEW-004',
    name: 'Octopus Agile arbitrage opportunity',
    category: 'revenue-enhancement',
    description: 'Agile variable pricing delivers 3-4x revenue vs fixed tariffs for automated battery systems.',
    probability: 5,
    impact: 4,
    score: 20,
    rating: opportunityRating(20),
    captureStrategy: 'Default all new deployments to Agile, invest in automation.',
    captureOwner: 'Dave',
    captureStatus: 'in-progress',
    expectedValue: 75000,
    triggerThreshold: 'Agile arbitrage revenue exceeds IOF revenue for 3 consecutive months',
    dependencies: ['Automated charge/discharge scheduling', 'Agile API integration'],
    investmentRequired: 'Software development for automation platform',
    lastReviewed: new Date('2026-03-25'),
  },
];

// ============================================================
// Score History (simulated)
// ============================================================

export interface ScoreHistoryEntry {
  date: string;
  probability: number;
  impact: number;
  score: number;
}

export function generateScoreHistory(item: RiskItem | OpportunityItem): ScoreHistoryEntry[] {
  const entries: ScoreHistoryEntry[] = [];
  const months = ['2025-10', '2025-11', '2025-12', '2026-01', '2026-02', '2026-03'];

  for (let i = 0; i < months.length; i++) {
    const jitter = Math.sin(i * 1.5 + item.id.charCodeAt(4)) * 0.5;
    const prob = Math.max(1, Math.min(5, Math.round(item.probability + jitter)));
    const imp = item.impact;
    entries.push({
      date: months[i],
      probability: prob,
      impact: imp,
      score: prob * imp,
    });
  }

  return entries;
}

// ============================================================
// Timeline data
// ============================================================

export interface TimelineItem {
  id: string;
  name: string;
  type: 'risk' | 'opportunity';
  category: string;
  startMonth: number; // months from now
  endMonth: number;
  probability: number;
  score: number;
}

export function generateTimelineData(): TimelineItem[] {
  const items: TimelineItem[] = [];

  SEEDED_RISKS.forEach((r) => {
    const hash = r.id.charCodeAt(4) + r.id.charCodeAt(5);
    const start = (hash % 18);
    const duration = 6 + (hash % 24);
    items.push({
      id: r.id,
      name: r.name,
      type: 'risk',
      category: r.category,
      startMonth: start,
      endMonth: start + duration,
      probability: r.probability,
      score: r.score,
    });
  });

  SEEDED_OPPORTUNITIES.forEach((o) => {
    const hash = o.id.charCodeAt(4) + o.id.charCodeAt(5);
    const start = (hash % 12);
    const duration = 6 + (hash % 30);
    items.push({
      id: o.id,
      name: o.name,
      type: 'opportunity',
      category: o.category,
      startMonth: start,
      endMonth: start + duration,
      probability: o.probability,
      score: o.score,
    });
  });

  return items;
}
