// ============================================================
// Hardware Module — Seeded Data
// All batteries, inverters, solar panels, heat pumps
// ============================================================

import type {
  BatterySpec,
  InverterSpec,
  SolarPanelSpec,
  HeatPumpSpec,
  CompatibilityEntry,
} from './types';

// --- Batteries ---

export const batteries: BatterySpec[] = [
  {
    id: 'bat-sigenergy',
    manufacturer: 'Sigenergy',
    model: 'SigenStack 12kWh',
    category: 'battery',
    capacityPerModuleKwh: 12,
    maxModulesPerString: 8,
    chemistry: 'LFP',
    cycleLife: 8000,
    degradationRatePercent: 1.5,
    roundTripEfficiency: 96,
    chargeRateKw: 6,
    dischargeRateKw: 6,
    ipRating: 'IP65',
    weightKg: 125,
    operatingTempMin: -10,
    operatingTempMax: 50,
    warrantyYears: 15,
    wholesalePriceGbp: 4200,
    mcsCertified: true,
    iofCompatible: true,
    compatibleInverters: ['inv-sigenergy-m1', 'inv-givenergy', 'inv-victron'],
  },
  {
    id: 'bat-tesla-pw3',
    manufacturer: 'Tesla',
    model: 'Powerwall 3',
    category: 'battery',
    capacityPerModuleKwh: 13.5,
    maxModulesPerString: 4,
    chemistry: 'LFP',
    cycleLife: 6000,
    degradationRatePercent: 2.0,
    roundTripEfficiency: 97,
    chargeRateKw: 5,
    dischargeRateKw: 11.5,
    ipRating: 'IP67',
    weightKg: 130,
    operatingTempMin: -20,
    operatingTempMax: 50,
    warrantyYears: 10,
    wholesalePriceGbp: 7500,
    mcsCertified: true,
    iofCompatible: true,
    compatibleInverters: ['inv-tesla-gateway'],
    notes: 'Charge rate limited to 5kW in current firmware; 8kW planned. UK continuous discharge is 11.04kW AC.',
  },
  {
    id: 'bat-byd-hvs',
    manufacturer: 'BYD',
    model: 'Battery-Box Premium HVS',
    category: 'battery',
    capacityPerModuleKwh: 2.56,
    maxModulesPerString: 6,
    chemistry: 'LFP',
    cycleLife: 6000,
    degradationRatePercent: 1.8,
    roundTripEfficiency: 96,
    chargeRateKw: 5.12,
    dischargeRateKw: 5.12,
    ipRating: 'IP55',
    weightKg: 63,
    operatingTempMin: -10,
    operatingTempMax: 50,
    warrantyYears: 10,
    wholesalePriceGbp: 2800,
    mcsCertified: true,
    iofCompatible: false,
    compatibleInverters: ['inv-fronius', 'inv-sma', 'inv-victron', 'inv-huawei'],
  },
  {
    id: 'bat-byd-hvm',
    manufacturer: 'BYD',
    model: 'Battery-Box Premium HVM',
    category: 'battery',
    capacityPerModuleKwh: 2.76,
    maxModulesPerString: 8,
    chemistry: 'LFP',
    cycleLife: 6000,
    degradationRatePercent: 1.8,
    roundTripEfficiency: 95.3,
    chargeRateKw: 5.12,
    dischargeRateKw: 5.12,
    ipRating: 'IP55',
    weightKg: 63,
    operatingTempMin: -10,
    operatingTempMax: 50,
    warrantyYears: 10,
    wholesalePriceGbp: 2900,
    mcsCertified: true,
    iofCompatible: false,
    compatibleInverters: ['inv-fronius', 'inv-sma', 'inv-victron', 'inv-huawei'],
  },
  {
    id: 'bat-givenergy',
    manufacturer: 'GivEnergy',
    model: 'All-in-One 9.5kWh',
    category: 'battery',
    capacityPerModuleKwh: 9.5,
    maxModulesPerString: 4,
    chemistry: 'LFP',
    cycleLife: 6000,
    degradationRatePercent: 2.0,
    roundTripEfficiency: 94.5,
    chargeRateKw: 6.1,
    dischargeRateKw: 6.1,
    ipRating: 'IP65',
    weightKg: 85,
    operatingTempMin: 0,
    operatingTempMax: 50,
    warrantyYears: 12,
    wholesalePriceGbp: 3200,
    mcsCertified: true,
    iofCompatible: true,
    compatibleInverters: ['inv-givenergy'],
  },
  {
    id: 'bat-huawei-luna',
    manufacturer: 'Huawei',
    model: 'LUNA2000-10-S0',
    category: 'battery',
    capacityPerModuleKwh: 10,
    maxModulesPerString: 4,
    chemistry: 'LFP',
    cycleLife: 6000,
    degradationRatePercent: 1.8,
    roundTripEfficiency: 95,
    chargeRateKw: 5,
    dischargeRateKw: 5,
    ipRating: 'IP65',
    weightKg: 114,
    operatingTempMin: -10,
    operatingTempMax: 55,
    warrantyYears: 10,
    wholesalePriceGbp: 4000,
    mcsCertified: true,
    iofCompatible: false,
    compatibleInverters: ['inv-huawei'],
  },
  {
    id: 'bat-pylontech',
    manufacturer: 'Pylontech',
    model: 'Force H2 7.1kWh',
    category: 'battery',
    capacityPerModuleKwh: 7.1,
    maxModulesPerString: 8,
    chemistry: 'LFP',
    cycleLife: 6000,
    degradationRatePercent: 2.0,
    roundTripEfficiency: 95,
    chargeRateKw: 3.55,
    dischargeRateKw: 3.55,
    ipRating: 'IP55',
    weightKg: 82,
    operatingTempMin: 0,
    operatingTempMax: 50,
    warrantyYears: 10,
    wholesalePriceGbp: 2500,
    mcsCertified: true,
    iofCompatible: false,
    compatibleInverters: ['inv-solax', 'inv-fox-ess', 'inv-sunsynk', 'inv-victron'],
  },
  {
    id: 'bat-fox-ess',
    manufacturer: 'Fox ESS',
    model: 'ECS 10.4kWh',
    category: 'battery',
    capacityPerModuleKwh: 10.4,
    maxModulesPerString: 4,
    chemistry: 'LFP',
    cycleLife: 6000,
    degradationRatePercent: 2.0,
    roundTripEfficiency: 95,
    chargeRateKw: 5.2,
    dischargeRateKw: 5.2,
    ipRating: 'IP55',
    weightKg: 108,
    operatingTempMin: 0,
    operatingTempMax: 50,
    warrantyYears: 10,
    wholesalePriceGbp: 2600,
    mcsCertified: true,
    iofCompatible: true,
    compatibleInverters: ['inv-fox-ess'],
  },
  {
    id: 'bat-solax',
    manufacturer: 'SolaX',
    model: 'Triple Power T63 6.3kWh',
    category: 'battery',
    capacityPerModuleKwh: 6.3,
    maxModulesPerString: 4,
    chemistry: 'LFP',
    cycleLife: 6000,
    degradationRatePercent: 2.0,
    roundTripEfficiency: 95,
    chargeRateKw: 3.15,
    dischargeRateKw: 3.15,
    ipRating: 'IP55',
    weightKg: 68,
    operatingTempMin: 0,
    operatingTempMax: 50,
    warrantyYears: 10,
    wholesalePriceGbp: 2200,
    mcsCertified: true,
    iofCompatible: false,
    compatibleInverters: ['inv-solax'],
  },
  {
    id: 'bat-sunsynk',
    manufacturer: 'Sunsynk',
    model: 'ECCO 5.12kWh',
    category: 'battery',
    capacityPerModuleKwh: 5.12,
    maxModulesPerString: 8,
    chemistry: 'LFP',
    cycleLife: 6000,
    degradationRatePercent: 2.0,
    roundTripEfficiency: 95,
    chargeRateKw: 2.56,
    dischargeRateKw: 2.56,
    ipRating: 'IP55',
    weightKg: 52,
    operatingTempMin: 0,
    operatingTempMax: 45,
    warrantyYears: 10,
    wholesalePriceGbp: 1800,
    mcsCertified: true,
    iofCompatible: false,
    compatibleInverters: ['inv-sunsynk'],
  },
  {
    id: 'bat-alpha-ess',
    manufacturer: 'Alpha ESS',
    model: 'SMILE-G3 10.1kWh',
    category: 'battery',
    capacityPerModuleKwh: 10.1,
    maxModulesPerString: 5,
    chemistry: 'LFP',
    cycleLife: 6000,
    degradationRatePercent: 2.0,
    roundTripEfficiency: 95,
    chargeRateKw: 5,
    dischargeRateKw: 5,
    ipRating: 'IP55',
    weightKg: 100,
    operatingTempMin: 0,
    operatingTempMax: 50,
    warrantyYears: 10,
    wholesalePriceGbp: 3500,
    mcsCertified: true,
    iofCompatible: true,
    compatibleInverters: ['inv-solax', 'inv-sma', 'inv-victron'],
  },
  {
    id: 'bat-catl-naxtra',
    manufacturer: 'CATL',
    model: 'Naxtra 6.9kWh (Sodium-Ion)',
    category: 'battery',
    capacityPerModuleKwh: 6.9,
    maxModulesPerString: 6,
    chemistry: 'NaIon',
    cycleLife: 5000,
    degradationRatePercent: 2.5,
    roundTripEfficiency: 92,
    chargeRateKw: 3.45,
    dischargeRateKw: 3.45,
    ipRating: 'IP55',
    weightKg: 85,
    operatingTempMin: -20,
    operatingTempMax: 60,
    warrantyYears: 10,
    wholesalePriceGbp: 1600,
    mcsCertified: false,
    iofCompatible: false,
    compatibleInverters: ['inv-solax', 'inv-sunsynk', 'inv-victron'],
  },
  {
    id: 'bat-fogstar',
    manufacturer: 'Fogstar',
    model: 'Fogstar Energy 48.3kWh Stack (3 × 16.1kWh)',
    category: 'battery',
    capacityPerModuleKwh: 48.3,  // per stack (3 modules)
    maxModulesPerString: 1,       // 1 stack = 1 unit, parallel stacks for scaling
    chemistry: 'LFP',
    cycleLife: 8000,              // at 91% DOD
    degradationRatePercent: 2.0,
    roundTripEfficiency: 93,      // 48V LV system
    chargeRateKw: 15.36,          // 300A × 51.2V
    dischargeRateKw: 15.36,       // 300A × 51.2V
    ipRating: 'IP65',
    weightKg: 394,
    operatingTempMin: -15,        // with integrated heating
    operatingTempMax: 45,
    warrantyYears: 6,             // 6yr warranty, 10yr UK support
    wholesalePriceGbp: 4999,      // 3-module stack
    mcsCertified: true,
    iofCompatible: false,
    compatibleInverters: ['inv-victron', 'inv-sunsynk', 'inv-solax', 'inv-deye-20k'],
    notes: '314Ah LiFePO4. JK 2A active balancing. Built-in aerosol fire suppression. Integrated heating for charging to -15°C. 150A SEPLOS BMS. 350A breaker. LCD touchscreen. CAN/RS485 comms. Scales to 1.23MWh in parallel.',
  },
  {
    id: 'bat-fogstar-64',
    manufacturer: 'Fogstar',
    model: 'Fogstar Energy 64.4kWh Stack (4 × 16.1kWh)',
    category: 'battery',
    capacityPerModuleKwh: 64.4,  // per stack (4 modules)
    maxModulesPerString: 1,       // 1 stack = 1 unit
    chemistry: 'LFP',
    cycleLife: 8000,              // at 91% DOD
    degradationRatePercent: 2.0,
    roundTripEfficiency: 93,
    chargeRateKw: 15.36,          // 300A × 51.2V
    dischargeRateKw: 15.36,
    ipRating: 'IP65',
    weightKg: 525,
    operatingTempMin: -15,
    operatingTempMax: 45,
    warrantyYears: 6,
    wholesalePriceGbp: 5999,      // 4-module stack
    mcsCertified: true,
    iofCompatible: false,
    compatibleInverters: ['inv-victron', 'inv-sunsynk', 'inv-solax', 'inv-deye-20k'],
    notes: '314Ah LiFePO4. JK 2A active balancing. Built-in aerosol fire suppression. Integrated heating. 150A SEPLOS BMS. 350A breaker. Scales to 1.23MWh in parallel.',
  },
];

// --- Inverters ---

export const inverters: InverterSpec[] = [
  {
    id: 'inv-sigenergy-m1',
    manufacturer: 'Sigenergy',
    model: 'M1 100kW 3-Phase Hybrid',
    category: 'inverter',
    maxPvInputKw: 40,
    maxBatteryCapacityKwh: 96,
    mpptTrackers: 4,
    hybrid: true,
    threePhase: true,
    g99Compliant: true,
    iofCompatible: true,
    octopusApiIntegration: true,
    homeAssistantCompatible: true,
    priceGbp: 8500,
    warrantyYears: 15,
    maxOutputKw: 100,
  },
  {
    id: 'inv-givenergy',
    manufacturer: 'GivEnergy',
    model: 'Giv-HY 6.0 3-Phase',
    category: 'inverter',
    maxPvInputKw: 12,
    maxBatteryCapacityKwh: 38,
    mpptTrackers: 2,
    hybrid: true,
    threePhase: true,
    g99Compliant: true,
    iofCompatible: true,
    octopusApiIntegration: true,
    homeAssistantCompatible: true,
    priceGbp: 2800,
    warrantyYears: 12,
    maxOutputKw: 6,
  },
  {
    id: 'inv-deye-20k',
    manufacturer: 'Deye',
    model: 'SUN-20K-SG05LP3-EU-SM2 20kW 3-Phase Hybrid LV',
    category: 'inverter',
    maxPvInputKw: 32,
    maxBatteryCapacityKwh: 999, // LV 48V bus, limited by BMS not inverter
    mpptTrackers: 2,
    hybrid: true,
    threePhase: true,
    g99Compliant: true, // VDE 4105, EN 50549, IEC 62109
    iofCompatible: false,
    octopusApiIntegration: false,
    homeAssistantCompatible: true,
    priceGbp: 2300, // ~€2,700
    warrantyYears: 10,
    maxOutputKw: 20, // 20kW AC output, 97.6% max efficiency
    // Battery: 40-60V range, 350A max charge/discharge, RS485/CAN
    // IP65, -40°C to +60°C, on-grid/off-grid/UPS modes
    // Compatible: NKON ESS, Pylontech US5000, Dyness, Fogstar (48V LFP)
  },
  {
    id: 'inv-solax',
    manufacturer: 'SolaX',
    model: 'X3-Hybrid G4 10kW',
    category: 'inverter',
    maxPvInputKw: 15,
    maxBatteryCapacityKwh: 63,
    mpptTrackers: 3,
    hybrid: true,
    threePhase: true,
    g99Compliant: true,
    iofCompatible: false,
    octopusApiIntegration: false,
    homeAssistantCompatible: true,
    priceGbp: 2400,
    warrantyYears: 10,
    maxOutputKw: 10,
  },
  {
    id: 'inv-fox-ess',
    manufacturer: 'Fox ESS',
    model: 'H3 12kW 3-Phase',
    category: 'inverter',
    maxPvInputKw: 16,
    maxBatteryCapacityKwh: 41.6,
    mpptTrackers: 2,
    hybrid: true,
    threePhase: true,
    g99Compliant: true,
    iofCompatible: true,
    octopusApiIntegration: false,
    homeAssistantCompatible: true,
    priceGbp: 2200,
    warrantyYears: 10,
    maxOutputKw: 12,
  },
  {
    id: 'inv-sunsynk',
    manufacturer: 'Sunsynk',
    model: '8kW 3-Phase Hybrid',
    category: 'inverter',
    maxPvInputKw: 12,
    maxBatteryCapacityKwh: 40.96,
    mpptTrackers: 2,
    hybrid: true,
    threePhase: true,
    g99Compliant: true,
    iofCompatible: false,
    octopusApiIntegration: false,
    homeAssistantCompatible: true,
    priceGbp: 1900,
    warrantyYears: 10,
    maxOutputKw: 8,
  },
  {
    id: 'inv-huawei',
    manufacturer: 'Huawei',
    model: 'SUN2000 10KTL-M1 3-Phase',
    category: 'inverter',
    maxPvInputKw: 15,
    maxBatteryCapacityKwh: 40,
    mpptTrackers: 2,
    hybrid: true,
    threePhase: true,
    g99Compliant: true,
    iofCompatible: false,
    octopusApiIntegration: false,
    homeAssistantCompatible: true,
    priceGbp: 2600,
    warrantyYears: 10,
    maxOutputKw: 10,
  },
  {
    id: 'inv-fronius',
    manufacturer: 'Fronius',
    model: 'Symo GEN24 10.0 Plus',
    category: 'inverter',
    maxPvInputKw: 15,
    maxBatteryCapacityKwh: 30.72,
    mpptTrackers: 2,
    hybrid: true,
    threePhase: true,
    g99Compliant: true,
    iofCompatible: false,
    octopusApiIntegration: false,
    homeAssistantCompatible: true,
    priceGbp: 2900,
    warrantyYears: 10,
    maxOutputKw: 10,
  },
  {
    id: 'inv-sma',
    manufacturer: 'SMA',
    model: 'Sunny Tripower 10.0 SE',
    category: 'inverter',
    maxPvInputKw: 15,
    maxBatteryCapacityKwh: 30.72,
    mpptTrackers: 2,
    hybrid: true,
    threePhase: true,
    g99Compliant: true,
    iofCompatible: false,
    octopusApiIntegration: false,
    homeAssistantCompatible: true,
    priceGbp: 3100,
    warrantyYears: 10,
    maxOutputKw: 10,
  },
  {
    id: 'inv-victron',
    manufacturer: 'Victron',
    model: 'MultiPlus-II 48/5000/70-50',
    category: 'inverter',
    maxPvInputKw: 10,
    maxBatteryCapacityKwh: 100,
    mpptTrackers: 0,
    hybrid: false,
    threePhase: true,
    g99Compliant: true,
    iofCompatible: false,
    octopusApiIntegration: false,
    homeAssistantCompatible: true,
    priceGbp: 1800,
    warrantyYears: 5,
    maxOutputKw: 5,
  },
  {
    id: 'inv-tesla-gateway',
    manufacturer: 'Tesla',
    model: 'Powerwall 3 Integrated Inverter',
    category: 'inverter',
    maxPvInputKw: 11.5,
    maxBatteryCapacityKwh: 54,
    mpptTrackers: 4,
    hybrid: true,
    threePhase: false,
    g99Compliant: true,
    iofCompatible: true,
    octopusApiIntegration: true,
    homeAssistantCompatible: true,
    priceGbp: 0,
    warrantyYears: 10,
    maxOutputKw: 11.5,
  },
];

// --- Solar Panels ---

export const solarPanels: SolarPanelSpec[] = [
  {
    id: 'sol-longi-himo7',
    manufacturer: 'LONGi',
    model: 'Hi-MO 7 580W',
    category: 'solar',
    wattage: 580,
    efficiency: 22.5,
    panelType: 'monocrystalline',
    warrantyYears: 30,
    degradationRatePercent: 0.4,
    dimensions: '2278x1134x30mm',
    weightKg: 28.5,
    priceGbp: 195,
    tempCoefficientPercent: -0.29,
  },
  {
    id: 'sol-jinko-tiger-neo',
    manufacturer: 'JinkoSolar',
    model: 'Tiger Neo 570W',
    category: 'solar',
    wattage: 570,
    efficiency: 22.3,
    panelType: 'monocrystalline',
    warrantyYears: 30,
    degradationRatePercent: 0.4,
    dimensions: '2278x1134x30mm',
    weightKg: 28.2,
    priceGbp: 185,
    tempCoefficientPercent: -0.30,
  },
  {
    id: 'sol-canadian-topbihiku',
    manufacturer: 'Canadian Solar',
    model: 'TOPBiHiKu7 585W',
    category: 'solar',
    wattage: 585,
    efficiency: 22.8,
    panelType: 'monocrystalline',
    warrantyYears: 25,
    degradationRatePercent: 0.45,
    dimensions: '2278x1134x35mm',
    weightKg: 29.0,
    priceGbp: 200,
    tempCoefficientPercent: -0.29,
  },
  {
    id: 'sol-trina-vertex-s',
    manufacturer: 'Trina Solar',
    model: 'Vertex S+ 445W',
    category: 'solar',
    wattage: 445,
    efficiency: 22.2,
    panelType: 'monocrystalline',
    warrantyYears: 25,
    degradationRatePercent: 0.45,
    dimensions: '1762x1134x30mm',
    weightKg: 21.8,
    priceGbp: 155,
    tempCoefficientPercent: -0.29,
  },
  {
    id: 'sol-sunpower-maxeon',
    manufacturer: 'SunPower',
    model: 'Maxeon 7 430W',
    category: 'solar',
    wattage: 430,
    efficiency: 24.1,
    panelType: 'monocrystalline',
    warrantyYears: 40,
    degradationRatePercent: 0.25,
    dimensions: '1872x1032x40mm',
    weightKg: 22.0,
    priceGbp: 350,
    tempCoefficientPercent: -0.27,
  },
  {
    id: 'sol-rec-alpha-pure',
    manufacturer: 'REC',
    model: 'Alpha Pure-RX 470W',
    category: 'solar',
    wattage: 470,
    efficiency: 22.6,
    panelType: 'monocrystalline',
    warrantyYears: 25,
    degradationRatePercent: 0.25,
    dimensions: '2056x1032x30mm',
    weightKg: 22.5,
    priceGbp: 280,
    tempCoefficientPercent: -0.26,
  },
];

// --- Heat Pumps ---

export const heatPumps: HeatPumpSpec[] = [
  {
    id: 'hp-mitsubishi-ecodan',
    manufacturer: 'Mitsubishi',
    model: 'Ecodan R290 PUZ-WZ 8.5kW',
    category: 'heat-pump',
    copRating: 4.2,
    copAtMinus5: 2.8,
    heatingCapacityKw: 8.5,
    noiseDb: 45,
    refrigerant: 'R290',
    mcsCertified: true,
    priceGbp: 6500,
    warrantyYears: 7,
    suitableForLancashire: true,
    smartTariffIntegration: true,
  },
  {
    id: 'hp-daikin-altherma',
    manufacturer: 'Daikin',
    model: 'Altherma 3 H HT 9kW',
    category: 'heat-pump',
    copRating: 4.0,
    copAtMinus5: 2.6,
    heatingCapacityKw: 9,
    noiseDb: 47,
    refrigerant: 'R290',
    mcsCertified: true,
    priceGbp: 7200,
    warrantyYears: 5,
    suitableForLancashire: true,
    smartTariffIntegration: true,
  },
  {
    id: 'hp-samsung-ehs',
    manufacturer: 'Samsung',
    model: 'EHS Mono HT Quiet 12kW',
    category: 'heat-pump',
    copRating: 3.8,
    copAtMinus5: 2.5,
    heatingCapacityKw: 12,
    noiseDb: 40,
    refrigerant: 'R32',
    mcsCertified: true,
    priceGbp: 5800,
    warrantyYears: 5,
    suitableForLancashire: true,
    smartTariffIntegration: false,
  },
  {
    id: 'hp-vaillant-arotherm',
    manufacturer: 'Vaillant',
    model: 'aroTHERM plus 7kW',
    category: 'heat-pump',
    copRating: 5.4,
    copAtMinus5: 3.0,
    heatingCapacityKw: 7,
    noiseDb: 42,
    refrigerant: 'R290',
    mcsCertified: true,
    priceGbp: 7800,
    warrantyYears: 7,
    suitableForLancashire: true,
    smartTariffIntegration: true,
  },
  {
    id: 'hp-grant-aerona3',
    manufacturer: 'Grant',
    model: 'Aerona3 R32 10kW',
    category: 'heat-pump',
    copRating: 3.6,
    copAtMinus5: 2.4,
    heatingCapacityKw: 10,
    noiseDb: 48,
    refrigerant: 'R32',
    mcsCertified: true,
    priceGbp: 5200,
    warrantyYears: 5,
    suitableForLancashire: true,
    smartTariffIntegration: false,
  },
];

// --- Compatibility Matrix ---

export const compatibilityMatrix: CompatibilityEntry[] = [
  // Sigenergy batteries
  { batteryId: 'bat-sigenergy', inverterId: 'inv-sigenergy-m1', compatible: true, iofEligible: true, notes: 'Preferred pairing — native integration' },
  { batteryId: 'bat-sigenergy', inverterId: 'inv-givenergy', compatible: true, iofEligible: true, notes: 'Supported via CAN bus' },
  { batteryId: 'bat-sigenergy', inverterId: 'inv-victron', compatible: true, iofEligible: false },
  { batteryId: 'bat-sigenergy', inverterId: 'inv-solax', compatible: false, iofEligible: false },
  { batteryId: 'bat-sigenergy', inverterId: 'inv-fox-ess', compatible: false, iofEligible: false },
  { batteryId: 'bat-sigenergy', inverterId: 'inv-sunsynk', compatible: false, iofEligible: false },
  { batteryId: 'bat-sigenergy', inverterId: 'inv-huawei', compatible: false, iofEligible: false },
  { batteryId: 'bat-sigenergy', inverterId: 'inv-fronius', compatible: false, iofEligible: false },
  { batteryId: 'bat-sigenergy', inverterId: 'inv-sma', compatible: false, iofEligible: false },

  // Tesla
  { batteryId: 'bat-tesla-pw3', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-tesla-pw3', inverterId: 'inv-givenergy', compatible: false, iofEligible: false },
  { batteryId: 'bat-tesla-pw3', inverterId: 'inv-solax', compatible: false, iofEligible: false },
  { batteryId: 'bat-tesla-pw3', inverterId: 'inv-fox-ess', compatible: false, iofEligible: false },
  { batteryId: 'bat-tesla-pw3', inverterId: 'inv-sunsynk', compatible: false, iofEligible: false },
  { batteryId: 'bat-tesla-pw3', inverterId: 'inv-huawei', compatible: false, iofEligible: false },
  { batteryId: 'bat-tesla-pw3', inverterId: 'inv-fronius', compatible: false, iofEligible: false },
  { batteryId: 'bat-tesla-pw3', inverterId: 'inv-sma', compatible: false, iofEligible: false },
  { batteryId: 'bat-tesla-pw3', inverterId: 'inv-victron', compatible: false, iofEligible: false, notes: 'Tesla integrated inverter only' },
  { batteryId: 'bat-tesla-pw3', inverterId: 'inv-tesla-gateway', compatible: true, iofEligible: true, notes: 'Native pairing — integrated inverter' },

  // BYD HVS
  { batteryId: 'bat-byd-hvs', inverterId: 'inv-fronius', compatible: true, iofEligible: false, notes: 'Official BYD partner' },
  { batteryId: 'bat-byd-hvs', inverterId: 'inv-sma', compatible: true, iofEligible: false, notes: 'Official BYD partner' },
  { batteryId: 'bat-byd-hvs', inverterId: 'inv-victron', compatible: true, iofEligible: false },
  { batteryId: 'bat-byd-hvs', inverterId: 'inv-huawei', compatible: true, iofEligible: true },
  { batteryId: 'bat-byd-hvs', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-byd-hvs', inverterId: 'inv-givenergy', compatible: false, iofEligible: false },
  { batteryId: 'bat-byd-hvs', inverterId: 'inv-solax', compatible: false, iofEligible: false },
  { batteryId: 'bat-byd-hvs', inverterId: 'inv-fox-ess', compatible: false, iofEligible: false },
  { batteryId: 'bat-byd-hvs', inverterId: 'inv-sunsynk', compatible: false, iofEligible: false },

  // BYD HVM
  { batteryId: 'bat-byd-hvm', inverterId: 'inv-fronius', compatible: true, iofEligible: false },
  { batteryId: 'bat-byd-hvm', inverterId: 'inv-sma', compatible: true, iofEligible: false },
  { batteryId: 'bat-byd-hvm', inverterId: 'inv-victron', compatible: true, iofEligible: false },
  { batteryId: 'bat-byd-hvm', inverterId: 'inv-huawei', compatible: true, iofEligible: true },
  { batteryId: 'bat-byd-hvm', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-byd-hvm', inverterId: 'inv-givenergy', compatible: false, iofEligible: false },
  { batteryId: 'bat-byd-hvm', inverterId: 'inv-solax', compatible: false, iofEligible: false },
  { batteryId: 'bat-byd-hvm', inverterId: 'inv-fox-ess', compatible: false, iofEligible: false },
  { batteryId: 'bat-byd-hvm', inverterId: 'inv-sunsynk', compatible: false, iofEligible: false },

  // GivEnergy
  { batteryId: 'bat-givenergy', inverterId: 'inv-givenergy', compatible: true, iofEligible: true, notes: 'Native pairing — best integration' },
  { batteryId: 'bat-givenergy', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-givenergy', inverterId: 'inv-solax', compatible: false, iofEligible: false },
  { batteryId: 'bat-givenergy', inverterId: 'inv-fox-ess', compatible: false, iofEligible: false },
  { batteryId: 'bat-givenergy', inverterId: 'inv-sunsynk', compatible: false, iofEligible: false },
  { batteryId: 'bat-givenergy', inverterId: 'inv-huawei', compatible: false, iofEligible: false },
  { batteryId: 'bat-givenergy', inverterId: 'inv-fronius', compatible: false, iofEligible: false },
  { batteryId: 'bat-givenergy', inverterId: 'inv-sma', compatible: false, iofEligible: false },
  { batteryId: 'bat-givenergy', inverterId: 'inv-victron', compatible: false, iofEligible: false },

  // Huawei LUNA
  { batteryId: 'bat-huawei-luna', inverterId: 'inv-huawei', compatible: true, iofEligible: true, notes: 'Native pairing — mandatory' },
  { batteryId: 'bat-huawei-luna', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-huawei-luna', inverterId: 'inv-givenergy', compatible: false, iofEligible: false },
  { batteryId: 'bat-huawei-luna', inverterId: 'inv-solax', compatible: false, iofEligible: false },
  { batteryId: 'bat-huawei-luna', inverterId: 'inv-fox-ess', compatible: false, iofEligible: false },
  { batteryId: 'bat-huawei-luna', inverterId: 'inv-sunsynk', compatible: false, iofEligible: false },
  { batteryId: 'bat-huawei-luna', inverterId: 'inv-fronius', compatible: false, iofEligible: false },
  { batteryId: 'bat-huawei-luna', inverterId: 'inv-sma', compatible: false, iofEligible: false },
  { batteryId: 'bat-huawei-luna', inverterId: 'inv-victron', compatible: false, iofEligible: false },

  // Pylontech
  { batteryId: 'bat-pylontech', inverterId: 'inv-solax', compatible: true, iofEligible: false },
  { batteryId: 'bat-pylontech', inverterId: 'inv-fox-ess', compatible: true, iofEligible: false },
  { batteryId: 'bat-pylontech', inverterId: 'inv-sunsynk', compatible: true, iofEligible: false },
  { batteryId: 'bat-pylontech', inverterId: 'inv-victron', compatible: true, iofEligible: false },
  { batteryId: 'bat-pylontech', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-pylontech', inverterId: 'inv-givenergy', compatible: false, iofEligible: false },
  { batteryId: 'bat-pylontech', inverterId: 'inv-huawei', compatible: false, iofEligible: false },
  { batteryId: 'bat-pylontech', inverterId: 'inv-fronius', compatible: false, iofEligible: false },
  { batteryId: 'bat-pylontech', inverterId: 'inv-sma', compatible: false, iofEligible: false },

  // Fox ESS
  { batteryId: 'bat-fox-ess', inverterId: 'inv-fox-ess', compatible: true, iofEligible: false, notes: 'Native pairing' },
  { batteryId: 'bat-fox-ess', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-fox-ess', inverterId: 'inv-givenergy', compatible: false, iofEligible: false },
  { batteryId: 'bat-fox-ess', inverterId: 'inv-solax', compatible: false, iofEligible: false },
  { batteryId: 'bat-fox-ess', inverterId: 'inv-sunsynk', compatible: false, iofEligible: false },
  { batteryId: 'bat-fox-ess', inverterId: 'inv-huawei', compatible: false, iofEligible: false },
  { batteryId: 'bat-fox-ess', inverterId: 'inv-fronius', compatible: false, iofEligible: false },
  { batteryId: 'bat-fox-ess', inverterId: 'inv-sma', compatible: false, iofEligible: false },
  { batteryId: 'bat-fox-ess', inverterId: 'inv-victron', compatible: false, iofEligible: false },

  // SolaX
  { batteryId: 'bat-solax', inverterId: 'inv-solax', compatible: true, iofEligible: false, notes: 'Native pairing' },
  { batteryId: 'bat-solax', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-solax', inverterId: 'inv-givenergy', compatible: false, iofEligible: false },
  { batteryId: 'bat-solax', inverterId: 'inv-fox-ess', compatible: false, iofEligible: false },
  { batteryId: 'bat-solax', inverterId: 'inv-sunsynk', compatible: false, iofEligible: false },
  { batteryId: 'bat-solax', inverterId: 'inv-huawei', compatible: false, iofEligible: false },
  { batteryId: 'bat-solax', inverterId: 'inv-fronius', compatible: false, iofEligible: false },
  { batteryId: 'bat-solax', inverterId: 'inv-sma', compatible: false, iofEligible: false },
  { batteryId: 'bat-solax', inverterId: 'inv-victron', compatible: false, iofEligible: false },

  // Sunsynk
  { batteryId: 'bat-sunsynk', inverterId: 'inv-sunsynk', compatible: true, iofEligible: false, notes: 'Native pairing' },
  { batteryId: 'bat-sunsynk', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-sunsynk', inverterId: 'inv-givenergy', compatible: false, iofEligible: false },
  { batteryId: 'bat-sunsynk', inverterId: 'inv-solax', compatible: false, iofEligible: false },
  { batteryId: 'bat-sunsynk', inverterId: 'inv-fox-ess', compatible: false, iofEligible: false },
  { batteryId: 'bat-sunsynk', inverterId: 'inv-huawei', compatible: false, iofEligible: false },
  { batteryId: 'bat-sunsynk', inverterId: 'inv-fronius', compatible: false, iofEligible: false },
  { batteryId: 'bat-sunsynk', inverterId: 'inv-sma', compatible: false, iofEligible: false },
  { batteryId: 'bat-sunsynk', inverterId: 'inv-victron', compatible: false, iofEligible: false },

  // Alpha ESS
  { batteryId: 'bat-alpha-ess', inverterId: 'inv-solax', compatible: true, iofEligible: false },
  { batteryId: 'bat-alpha-ess', inverterId: 'inv-sma', compatible: true, iofEligible: false },
  { batteryId: 'bat-alpha-ess', inverterId: 'inv-victron', compatible: true, iofEligible: false },
  { batteryId: 'bat-alpha-ess', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-alpha-ess', inverterId: 'inv-givenergy', compatible: false, iofEligible: false },
  { batteryId: 'bat-alpha-ess', inverterId: 'inv-fox-ess', compatible: false, iofEligible: false },
  { batteryId: 'bat-alpha-ess', inverterId: 'inv-sunsynk', compatible: false, iofEligible: false },
  { batteryId: 'bat-alpha-ess', inverterId: 'inv-huawei', compatible: false, iofEligible: false },
  { batteryId: 'bat-alpha-ess', inverterId: 'inv-fronius', compatible: false, iofEligible: false },

  // CATL Naxtra
  { batteryId: 'bat-catl-naxtra', inverterId: 'inv-solax', compatible: true, iofEligible: false, notes: 'Sodium-ion — emerging tech' },
  { batteryId: 'bat-catl-naxtra', inverterId: 'inv-sunsynk', compatible: true, iofEligible: false },
  { batteryId: 'bat-catl-naxtra', inverterId: 'inv-victron', compatible: true, iofEligible: false },
  { batteryId: 'bat-catl-naxtra', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-catl-naxtra', inverterId: 'inv-givenergy', compatible: false, iofEligible: false },
  { batteryId: 'bat-catl-naxtra', inverterId: 'inv-fox-ess', compatible: false, iofEligible: false },
  { batteryId: 'bat-catl-naxtra', inverterId: 'inv-huawei', compatible: false, iofEligible: false },
  { batteryId: 'bat-catl-naxtra', inverterId: 'inv-fronius', compatible: false, iofEligible: false },
  { batteryId: 'bat-catl-naxtra', inverterId: 'inv-sma', compatible: false, iofEligible: false },

  // Fogstar
  { batteryId: 'bat-fogstar', inverterId: 'inv-victron', compatible: true, iofEligible: false },
  { batteryId: 'bat-fogstar', inverterId: 'inv-sunsynk', compatible: true, iofEligible: false },
  { batteryId: 'bat-fogstar', inverterId: 'inv-solax', compatible: true, iofEligible: false },
  { batteryId: 'bat-fogstar', inverterId: 'inv-deye-20k', compatible: true, iofEligible: false },
  { batteryId: 'bat-fogstar', inverterId: 'inv-sigenergy-m1', compatible: false, iofEligible: false },
  { batteryId: 'bat-fogstar', inverterId: 'inv-givenergy', compatible: false, iofEligible: false },
  { batteryId: 'bat-fogstar', inverterId: 'inv-fox-ess', compatible: false, iofEligible: false },
  { batteryId: 'bat-fogstar', inverterId: 'inv-huawei', compatible: false, iofEligible: false },
  { batteryId: 'bat-fogstar', inverterId: 'inv-fronius', compatible: false, iofEligible: false },
  { batteryId: 'bat-fogstar', inverterId: 'inv-sma', compatible: false, iofEligible: false },
  // Fogstar 64.4kWh stack compatibility
  { batteryId: 'bat-fogstar-64', inverterId: 'inv-victron', compatible: true, iofEligible: false },
  { batteryId: 'bat-fogstar-64', inverterId: 'inv-sunsynk', compatible: true, iofEligible: false },
  { batteryId: 'bat-fogstar-64', inverterId: 'inv-solax', compatible: true, iofEligible: false },
  { batteryId: 'bat-fogstar-64', inverterId: 'inv-deye-20k', compatible: true, iofEligible: false },
];
