// ============================================================
// Seeded ENWL Substation Data — East Lancashire (BB postcode areas)
// Based on Electricity North West substation locations
// ============================================================

import type { Substation } from '@/shared/types';

export const substations: Substation[] = [
  {
    id: 'enwl-bb1-001',
    name: 'Blackburn Central 33/11kV',
    dnoRegion: 'ENWL',
    latitude: 53.7488,
    longitude: -2.4828,
    capacityMva: 45,
    currentLoadPercent: 78,
    constraintStatus: 'approaching',
    flexibilityTenderActive: true,
    connectedHomes: 3200,
    maxNewConnections: 120,
  },
  {
    id: 'enwl-bb1-002',
    name: 'Blackburn East 33/11kV',
    dnoRegion: 'ENWL',
    latitude: 53.7520,
    longitude: -2.4600,
    capacityMva: 30,
    currentLoadPercent: 62,
    constraintStatus: 'unconstrained',
    flexibilityTenderActive: false,
    connectedHomes: 2100,
    maxNewConnections: 280,
  },
  {
    id: 'enwl-bb2-001',
    name: 'Darwen 33/11kV',
    dnoRegion: 'ENWL',
    latitude: 53.6980,
    longitude: -2.4600,
    capacityMva: 25,
    currentLoadPercent: 71,
    constraintStatus: 'approaching',
    flexibilityTenderActive: true,
    connectedHomes: 1800,
    maxNewConnections: 90,
  },
  {
    id: 'enwl-bb3-001',
    name: 'Great Harwood 33/11kV',
    dnoRegion: 'ENWL',
    latitude: 53.7870,
    longitude: -2.4070,
    capacityMva: 20,
    currentLoadPercent: 55,
    constraintStatus: 'unconstrained',
    flexibilityTenderActive: false,
    connectedHomes: 1200,
    maxNewConnections: 300,
  },
  {
    id: 'enwl-bb4-001',
    name: 'Rossendale 33/11kV',
    dnoRegion: 'ENWL',
    latitude: 53.6870,
    longitude: -2.2750,
    capacityMva: 22,
    currentLoadPercent: 88,
    constraintStatus: 'constrained',
    flexibilityTenderActive: true,
    connectedHomes: 1500,
    maxNewConnections: 25,
  },
  {
    id: 'enwl-bb5-001',
    name: 'Accrington 33/11kV',
    dnoRegion: 'ENWL',
    latitude: 53.7536,
    longitude: -2.3638,
    capacityMva: 35,
    currentLoadPercent: 82,
    constraintStatus: 'approaching',
    flexibilityTenderActive: true,
    connectedHomes: 2400,
    maxNewConnections: 85,
  },
  {
    id: 'enwl-bb5-002',
    name: 'Oswaldtwistle 11kV',
    dnoRegion: 'ENWL',
    latitude: 53.7440,
    longitude: -2.3930,
    capacityMva: 15,
    currentLoadPercent: 45,
    constraintStatus: 'unconstrained',
    flexibilityTenderActive: false,
    connectedHomes: 900,
    maxNewConnections: 350,
  },
  {
    id: 'enwl-bb6-001',
    name: 'Burnley Central 33/11kV',
    dnoRegion: 'ENWL',
    latitude: 53.7890,
    longitude: -2.2480,
    capacityMva: 40,
    currentLoadPercent: 74,
    constraintStatus: 'approaching',
    flexibilityTenderActive: true,
    connectedHomes: 2800,
    maxNewConnections: 150,
  },
  {
    id: 'enwl-bb7-001',
    name: 'Clitheroe 33/11kV',
    dnoRegion: 'ENWL',
    latitude: 53.8710,
    longitude: -2.3920,
    capacityMva: 18,
    currentLoadPercent: 42,
    constraintStatus: 'unconstrained',
    flexibilityTenderActive: false,
    connectedHomes: 800,
    maxNewConnections: 400,
  },
  {
    id: 'enwl-bb8-001',
    name: 'Padiham 11kV',
    dnoRegion: 'ENWL',
    latitude: 53.7970,
    longitude: -2.3130,
    capacityMva: 12,
    currentLoadPercent: 91,
    constraintStatus: 'constrained',
    flexibilityTenderActive: true,
    connectedHomes: 700,
    maxNewConnections: 10,
  },
  {
    id: 'enwl-bb9-001',
    name: 'Pendle 33/11kV',
    dnoRegion: 'ENWL',
    latitude: 53.8550,
    longitude: -2.1650,
    capacityMva: 28,
    currentLoadPercent: 67,
    constraintStatus: 'unconstrained',
    flexibilityTenderActive: false,
    connectedHomes: 1900,
    maxNewConnections: 220,
  },
  {
    id: 'enwl-bb9-002',
    name: 'Nelson 11kV',
    dnoRegion: 'ENWL',
    latitude: 53.8350,
    longitude: -2.2180,
    capacityMva: 16,
    currentLoadPercent: 85,
    constraintStatus: 'constrained',
    flexibilityTenderActive: true,
    connectedHomes: 1100,
    maxNewConnections: 20,
  },
  {
    id: 'enwl-bb10-001',
    name: 'Whalley 11kV',
    dnoRegion: 'ENWL',
    latitude: 53.8220,
    longitude: -2.4100,
    capacityMva: 10,
    currentLoadPercent: 38,
    constraintStatus: 'unconstrained',
    flexibilityTenderActive: false,
    connectedHomes: 500,
    maxNewConnections: 300,
  },
  {
    id: 'enwl-bb11-001',
    name: 'Longridge 11kV',
    dnoRegion: 'ENWL',
    latitude: 53.8310,
    longitude: -2.5970,
    capacityMva: 14,
    currentLoadPercent: 52,
    constraintStatus: 'unconstrained',
    flexibilityTenderActive: false,
    connectedHomes: 650,
    maxNewConnections: 280,
  },
  {
    id: 'enwl-bb12-001',
    name: 'Haslingden 11kV',
    dnoRegion: 'ENWL',
    latitude: 53.7040,
    longitude: -2.3280,
    capacityMva: 13,
    currentLoadPercent: 76,
    constraintStatus: 'approaching',
    flexibilityTenderActive: false,
    connectedHomes: 850,
    maxNewConnections: 100,
  },
];

// Flexibility tender data keyed by substation ID
export const flexibilityTenders: Record<string, {
  tenderId: string;
  valuePerMwPerHour: number;
  totalAnnualValue: number;
  windowStart: string;
  windowEnd: string;
  seasonality: string;
  status: 'open' | 'awarded' | 'pending';
}> = {
  'enwl-bb1-001': {
    tenderId: 'FLEX-ENW-2026-001',
    valuePerMwPerHour: 85,
    totalAnnualValue: 42000,
    windowStart: '16:00',
    windowEnd: '19:00',
    seasonality: 'Winter peak',
    status: 'open',
  },
  'enwl-bb2-001': {
    tenderId: 'FLEX-ENW-2026-002',
    valuePerMwPerHour: 72,
    totalAnnualValue: 35000,
    windowStart: '16:30',
    windowEnd: '19:30',
    seasonality: 'Winter peak',
    status: 'open',
  },
  'enwl-bb4-001': {
    tenderId: 'FLEX-ENW-2026-003',
    valuePerMwPerHour: 110,
    totalAnnualValue: 58000,
    windowStart: '16:00',
    windowEnd: '20:00',
    seasonality: 'All year',
    status: 'open',
  },
  'enwl-bb5-001': {
    tenderId: 'FLEX-ENW-2026-004',
    valuePerMwPerHour: 95,
    totalAnnualValue: 48000,
    windowStart: '16:00',
    windowEnd: '19:00',
    seasonality: 'Winter peak',
    status: 'awarded',
  },
  'enwl-bb6-001': {
    tenderId: 'FLEX-ENW-2026-005',
    valuePerMwPerHour: 78,
    totalAnnualValue: 38000,
    windowStart: '17:00',
    windowEnd: '19:30',
    seasonality: 'Winter peak',
    status: 'open',
  },
  'enwl-bb8-001': {
    tenderId: 'FLEX-ENW-2026-006',
    valuePerMwPerHour: 120,
    totalAnnualValue: 65000,
    windowStart: '15:30',
    windowEnd: '20:00',
    seasonality: 'All year',
    status: 'open',
  },
  'enwl-bb9-002': {
    tenderId: 'FLEX-ENW-2026-007',
    valuePerMwPerHour: 105,
    totalAnnualValue: 52000,
    windowStart: '16:00',
    windowEnd: '19:00',
    seasonality: 'Winter peak',
    status: 'pending',
  },
};
