// ============================================================
// Strategy Module — Seeded Data
// Competitors, partnerships, emerging tech, moat strategies,
// expansion pathways
// ============================================================

import type {
  Competitor,
  Partnership,
  EmergingTech,
  MoatAction,
  StrategyInitiative,
} from './types';

// --- Competitors ---

export const competitors: Competitor[] = [
  {
    id: 'comp-moixa',
    name: 'Moixa / Lunar Energy',
    description: 'Pioneer in domestic battery aggregation. Acquired by Lunar Energy. National coverage with GridShare platform for fleet optimisation. Strong software and AI trading capabilities.',
    region: 'National',
    estimatedPortfolioSize: 5000,
    threat: 'high',
    strengths: ['Mature aggregation platform', 'Large existing fleet', 'Octopus partnership', 'AI optimisation'],
    weaknesses: ['Corporate overhead', 'Less local focus', 'Slower to deploy in specific regions'],
    latitude: 51.5074,
    longitude: -0.1278,
    website: 'https://www.lunar.energy',
  },
  {
    id: 'comp-social-energy',
    name: 'Social Energy',
    description: 'Energy supplier with integrated battery storage proposition. Offers battery leasing bundled with energy supply. Focused on combining supply and storage.',
    region: 'National',
    estimatedPortfolioSize: 2000,
    threat: 'medium',
    strengths: ['Vertically integrated supplier + storage', 'Simple consumer proposition', 'Own tariffs'],
    weaknesses: ['Financial instability rumours', 'Small portfolio', 'Limited hardware choice'],
    latitude: 51.4545,
    longitude: -2.5879,
  },
  {
    id: 'comp-powervault',
    name: 'Powervault',
    description: 'UK-designed battery manufacturer and fleet operator. Targets social housing and new-build markets. Second-life battery pioneer.',
    region: 'National',
    estimatedPortfolioSize: 3000,
    threat: 'medium',
    strengths: ['UK-manufactured hardware', 'Social housing relationships', 'Second-life battery IP'],
    weaknesses: ['Smaller brand recognition', 'Limited installer network', 'Narrow product range'],
    latitude: 51.5155,
    longitude: -0.1419,
  },
  {
    id: 'comp-octopus',
    name: 'Octopus Energy',
    description: 'Major energy supplier with growing interest in behind-the-meter storage. Operates Kraken platform. Could deploy own fleet at scale, becoming RoseStack\'s biggest potential competitor.',
    region: 'National',
    estimatedPortfolioSize: 500,
    threat: 'critical',
    strengths: ['Massive customer base', 'Kraken platform', 'Agile/Flux tariffs', 'Deep pockets', 'Brand trust'],
    weaknesses: ['Currently focused on supply not deployment', 'Slow to move into fleet ownership', 'Bureaucratic at scale'],
    latitude: 53.4808,
    longitude: -2.2426,
  },
];

// --- Partnerships ---

export const partnerships: Partnership[] = [
  {
    id: 'part-enwl',
    name: 'Electricity North West (ENWL)',
    type: 'dno',
    stage: 'outreach',
    contactName: 'Flexibility Services Team',
    description: 'Direct partnership for flexibility services. ENWL run flexibility tenders for constrained substations. RoseStack portfolio could bid into these tenders as an aggregated resource.',
    potentialHomes: 500,
    notes: 'Key relationship — they control grid access in our operating area. Need to attend next flexibility forum.',
    lastUpdated: new Date('2026-02-15'),
  },
  {
    id: 'part-burnley-cricket',
    name: 'Burnley Cricket Club',
    type: 'sports-club',
    stage: 'identified',
    description: 'Local cricket club with strong community ties. Potential referral network for members and their neighbours. Also a potential commercial deployment site for club building.',
    potentialHomes: 50,
    notes: 'Dave plays here — warm introduction possible. Club committee meets monthly.',
    lastUpdated: new Date('2026-03-01'),
  },
  {
    id: 'part-rugby-club',
    name: 'Burnley Rugby Club',
    type: 'sports-club',
    stage: 'identified',
    description: 'Community rugby club in East Lancashire. Similar referral network opportunity. Potential for club premises battery installation as showcase.',
    potentialHomes: 40,
    notes: 'Explore joint sports club approach — bundle cricket and rugby club partnerships.',
    lastUpdated: new Date('2026-03-10'),
  },
  {
    id: 'part-mcdermott-homes',
    name: 'McDermott Homes',
    type: 'housing-developer',
    stage: 'outreach',
    contactName: 'Sales Director',
    description: 'Regional housebuilder active in Lancashire. New-build partnership where battery is included from day one. Adds value to their homes and locks in ESA from completion.',
    potentialHomes: 200,
    notes: 'Active developments in Burnley and surrounding areas. FBC require PV on new builds already.',
    lastUpdated: new Date('2026-02-20'),
  },
  {
    id: 'part-solar-installer',
    name: 'SunGift Solar (NW)',
    type: 'solar-installer',
    stage: 'negotiation',
    contactName: 'Regional Manager',
    description: 'Established solar installer in the Northwest. Referral partnership where they recommend RoseStack battery add-on to their solar customers.',
    potentialHomes: 150,
    notes: 'Already install Sigenergy. Good technical alignment. Discussing referral fee structure.',
    lastUpdated: new Date('2026-03-15'),
  },
  {
    id: 'part-together-housing',
    name: 'Together Housing Group',
    type: 'social-housing',
    stage: 'identified',
    description: 'Large social housing provider in East Lancashire. Single decision-maker for large portfolios. ESA model very attractive — tenants get lower bills, housing association gets green credentials.',
    potentialHomes: 500,
    notes: 'Manage ~36,000 homes across Lancashire and Yorkshire. Massive opportunity if we can get in.',
    lastUpdated: new Date('2026-03-05'),
  },
];

// --- Emerging Technologies ---

export const emergingTech: EmergingTech[] = [
  {
    id: 'tech-sodium-ion',
    name: 'Sodium-Ion Batteries',
    category: 'Battery Chemistry',
    maturity: 'developing',
    relevance: 'high',
    description: 'CATL Naxtra and Faradion/Reliance commercialising sodium-ion cells. Lower energy density than LFP but much cheaper materials. No lithium, cobalt, or nickel dependency.',
    timelineYears: 2,
    keyPlayers: ['CATL', 'Faradion/Reliance', 'BYD', 'HiNa'],
    rosestackImplication: 'Could reduce battery costs by 30-40%. Watch for home storage form factor. May enable own-brand RoseStack module at lower cost.',
  },
  {
    id: 'tech-v2g',
    name: 'Vehicle-to-Grid (V2G)',
    category: 'EV Integration',
    maturity: 'developing',
    relevance: 'high',
    description: 'Bidirectional EV charging allowing cars to export to grid. Relevant for homes with EVs — Dave has ID Buzz and EQA. Could double effective storage capacity.',
    timelineYears: 2,
    keyPlayers: ['Octopus (Powerloop)', 'OVO', 'Indra', 'Wallbox', 'Volkswagen'],
    rosestackImplication: 'Homes with EVs could have 60-80kWh of dispatchable storage. Massive arbitrage potential. Need V2G-compatible charger and vehicle.',
  },
  {
    id: 'tech-solid-state',
    name: 'Solid-State Batteries',
    category: 'Battery Chemistry',
    maturity: 'emerging',
    relevance: 'medium',
    description: 'Higher energy density, safer, longer cycle life. Toyota, QuantumScape, Samsung SDI leading. Still 3-5 years from mass production for stationary storage.',
    timelineYears: 5,
    keyPlayers: ['Toyota', 'QuantumScape', 'Samsung SDI', 'Solid Power'],
    rosestackImplication: 'Long-term game changer for home storage density and safety. Monitor but no action needed now.',
  },
  {
    id: 'tech-ai-trading',
    name: 'AI-Optimised Trading Algorithms',
    category: 'Software',
    maturity: 'maturing',
    relevance: 'critical',
    description: 'Machine learning models for energy price prediction, battery dispatch optimisation, and portfolio-level trading. Some platforms already achieving 15-20% better returns than rule-based systems.',
    timelineYears: 1,
    keyPlayers: ['Moixa/Lunar', 'Octopus Kraken', 'Habitat Energy', 'Modo Energy'],
    rosestackImplication: 'Essential for maximising arbitrage revenue. Build or buy decision. Could license from existing platform or develop own IP over time.',
  },
  {
    id: 'tech-perovskite',
    name: 'Perovskite Solar Cells',
    category: 'Solar Technology',
    maturity: 'emerging',
    relevance: 'medium',
    description: 'Next-generation solar technology. Can be printed onto flexible substrates. Higher efficiency potential than silicon. Oxford PV leading in tandem cells.',
    timelineYears: 4,
    keyPlayers: ['Oxford PV', 'Swift Solar', 'Saule Technologies', 'CubicPV'],
    rosestackImplication: 'Could enable solar on surfaces currently not viable (north-facing, curved). More solar = more battery value. Watch Oxford PV commercialisation.',
  },
  {
    id: 'tech-hydrogen',
    name: 'Hydrogen Home Storage',
    category: 'Alternative Storage',
    maturity: 'emerging',
    relevance: 'low',
    description: 'Electrolysis + fuel cell for seasonal home energy storage. Very early stage for residential. Lavo has a product but it is expensive and large.',
    timelineYears: 7,
    keyPlayers: ['Lavo', 'SFC Energy', 'ITM Power'],
    rosestackImplication: 'Too early and too expensive for residential. Monitor as long-term alternative. Battery storage will dominate for the next decade.',
  },
];

// --- Moat Actions ---

export const moatActions: MoatAction[] = [
  {
    id: 'moat-substation-saturation',
    strategy: 'Substation Exclusivity',
    action: 'Saturate Hapton substation area before competitors',
    status: 'in-progress',
    priority: 'high',
    owner: 'Dave',
    targetDate: '2026-09',
    notes: 'First 10 homes should be in one substation area to prove the model and lock out competitors.',
  },
  {
    id: 'moat-own-brand',
    strategy: 'Own-Brand Hardware',
    action: 'Research RoseStack 12kWh module feasibility',
    status: 'not-started',
    priority: 'medium',
    owner: 'Dave',
    targetDate: '2027-06',
    notes: 'Reduce dependency on Sigenergy. Sodium-ion could make this viable at lower cost.',
  },
  {
    id: 'moat-software-platform',
    strategy: 'Software Platform',
    action: 'Build portfolio management platform with licensing potential',
    status: 'in-progress',
    priority: 'high',
    owner: 'Dave',
    notes: 'This platform (RoseStack) IS the moat. Design it to be licensable to other deployers.',
  },
  {
    id: 'moat-data-advantage',
    strategy: 'Data Advantage',
    action: 'Collect and analyse real-world performance data from portfolio',
    status: 'not-started',
    priority: 'high',
    owner: 'Dave',
    targetDate: '2026-12',
    notes: 'Every home generates performance data. Aggregate this for better trading, better installer training, and better hardware selection.',
  },
  {
    id: 'moat-homeowner-lockin',
    strategy: 'Homeowner Lock-in',
    action: 'Implement ESA contracts with 10-year terms and referral incentives',
    status: 'in-progress',
    priority: 'high',
    owner: 'Dave',
    notes: 'ESA with LoA clause creates long-term relationship. Referral network creates organic growth.',
  },
  {
    id: 'moat-regulatory',
    strategy: 'Regulatory Relationships',
    action: 'Become the local battery storage expert ENWL calls',
    status: 'not-started',
    priority: 'medium',
    owner: 'Dave',
    targetDate: '2027-03',
    notes: 'Attend ENWL flexibility forums. Publish case studies. Be visible in industry consultations.',
  },
  {
    id: 'moat-installer-network',
    strategy: 'Installer Network',
    action: 'Build exclusive installer partnerships in Lancashire',
    status: 'not-started',
    priority: 'medium',
    owner: 'Dave',
    targetDate: '2026-12',
    notes: 'Train and certify local installers. Exclusive agreements prevent them working with competitors.',
  },
];

// --- Strategy Timeline / Expansion Pathways ---

export const strategyInitiatives: StrategyInitiative[] = [
  // Phase 1: Foundation (Months 1-6)
  {
    id: 'init-first-10',
    name: 'Deploy First 10 Homes',
    phase: 'phase-1',
    category: 'geographic',
    startMonth: 1,
    durationMonths: 6,
    description: 'Install first 10 batteries in Hapton/Burnley area. Prove the ESA model and collect performance data.',
  },
  {
    id: 'init-enwl-relationship',
    name: 'Establish ENWL Relationship',
    phase: 'phase-1',
    category: 'partnership',
    startMonth: 1,
    durationMonths: 4,
    description: 'Attend flexibility forums. Register as flexibility provider. Build relationship with local ENWL team.',
  },
  {
    id: 'init-platform-v1',
    name: 'RoseStack Platform v1',
    phase: 'phase-1',
    category: 'vertical',
    startMonth: 1,
    durationMonths: 6,
    description: 'Build core portfolio management, financial modelling, and customer acquisition platform.',
  },
  {
    id: 'init-sports-clubs',
    name: 'Sports Club Partnerships',
    phase: 'phase-1',
    category: 'partnership',
    startMonth: 2,
    durationMonths: 4,
    description: 'Sign referral agreements with Burnley cricket and rugby clubs. Install showcase battery at club premises.',
  },
  // Phase 2: Growth (Months 7-18)
  {
    id: 'init-50-homes',
    name: 'Scale to 50 Homes',
    phase: 'phase-2',
    category: 'geographic',
    startMonth: 7,
    durationMonths: 12,
    description: 'Expand across East Lancashire. Target multiple substation areas. Build installer capacity.',
  },
  {
    id: 'init-housing-developers',
    name: 'New-Build Developer Deals',
    phase: 'phase-2',
    category: 'partnership',
    startMonth: 8,
    durationMonths: 6,
    description: 'Sign partnership with McDermott Homes and other regional developers. Battery-included new builds.',
  },
  {
    id: 'init-social-housing',
    name: 'Social Housing Pilot',
    phase: 'phase-2',
    category: 'partnership',
    startMonth: 10,
    durationMonths: 8,
    description: 'Pilot with Together Housing. 20-home trial in social housing stock. Prove fuel poverty reduction.',
  },
  {
    id: 'init-ai-trading',
    name: 'AI Trading Algorithm',
    phase: 'phase-2',
    category: 'vertical',
    startMonth: 7,
    durationMonths: 6,
    description: 'Develop or license AI-optimised dispatch algorithm. Move beyond simple tariff arbitrage to ML-based trading.',
  },
  {
    id: 'init-flexibility',
    name: 'ENWL Flexibility Tenders',
    phase: 'phase-2',
    category: 'moat',
    startMonth: 9,
    durationMonths: 3,
    description: 'Bid into ENWL flexibility tenders with aggregated portfolio. New revenue stream.',
  },
  // Phase 3: Regional Scale (Months 19-36)
  {
    id: 'init-200-homes',
    name: 'Scale to 200 Homes',
    phase: 'phase-3',
    category: 'geographic',
    startMonth: 19,
    durationMonths: 18,
    description: 'Expand across Northwest England. Multiple DNO areas. Regional brand recognition.',
  },
  {
    id: 'init-own-brand',
    name: 'RoseStack Battery Module',
    phase: 'phase-3',
    category: 'moat',
    startMonth: 19,
    durationMonths: 12,
    description: 'Design and manufacture own-brand 12kWh battery module. Sodium-ion if viable. Reduce hardware dependency.',
  },
  {
    id: 'init-commercial',
    name: 'Commercial/Industrial Storage',
    phase: 'phase-3',
    category: 'adjacent',
    startMonth: 24,
    durationMonths: 12,
    description: 'Expand into C&I battery storage. Larger systems, higher revenue per site. Leverage platform and installer network.',
  },
  {
    id: 'init-platform-license',
    name: 'Platform Licensing',
    phase: 'phase-3',
    category: 'vertical',
    startMonth: 25,
    durationMonths: 6,
    description: 'License RoseStack platform to other battery deployers. SaaS revenue stream with high margins.',
  },
  // Phase 4: National (Months 37-60)
  {
    id: 'init-national',
    name: 'National Expansion',
    phase: 'phase-4',
    category: 'geographic',
    startMonth: 37,
    durationMonths: 24,
    description: 'Expand nationally. 1000+ home portfolio. Multiple DNO relationships. National brand.',
  },
  {
    id: 'init-ev-hubs',
    name: 'EV Charging Hubs',
    phase: 'phase-4',
    category: 'adjacent',
    startMonth: 37,
    durationMonths: 12,
    description: 'Battery-backed EV charging hubs. Combine grid storage with fast EV charging. High utilisation revenue.',
  },
  {
    id: 'init-community-energy',
    name: 'Community Energy Schemes',
    phase: 'phase-4',
    category: 'adjacent',
    startMonth: 42,
    durationMonths: 12,
    description: 'Community-owned battery projects. Parish/village level energy independence. Community share offers.',
  },
  {
    id: 'init-aggregation',
    name: 'Virtual Power Plant',
    phase: 'phase-4',
    category: 'vertical',
    startMonth: 40,
    durationMonths: 12,
    description: 'Full aggregation platform. Bid portfolio into national balancing mechanism. Virtual power plant operator.',
  },
];
