// ============================================================
// Product Design Module — Seeded Data from Research
// Sodium-ion cell options, inverters, costs, regulatory, manufacturing
// ============================================================

import type {
  SodiumIonCellSpec,
  PackDesign,
  BmsOption,
  InverterOption,
  CostModel,
  RegulatoryMilestone,
  ManufacturingOption,
  ImportLogistics,
} from './types';

// --- Sodium-Ion Cell Options ---

export const sodiumIonCells: SodiumIonCellSpec[] = [
  {
    id: 'cell-catl-naxtra',
    manufacturer: 'CATL',
    model: 'Naxtra EV',
    origin: 'China',
    chemistry: 'Na-ion',
    energyDensityWhKg: 175,
    nominalVoltage: 3.0,
    capacityAh: 100,
    cycleLife: 10000,
    operatingTempMin: -40,
    operatingTempMax: 70,
    chargeTempMin: -30,
    chargeTempMax: 60,
    fastChargeMinutes: 30,
    coldPerformanceRetention: 93,
    estimatedCellPriceUsdKwh: 40,
    estimatedPackPriceUsdKwh: 65,
    productionCapacityGwh: 50,
    status: 'mass-production',
    exportToUk: true,
    moqKwh: 500,
    certifications: ['UN38.3', 'IEC 62619', 'UL 9540A'],
    notes: 'World-leading Na-ion density. Deliveries to multiple customers from 2026. Cost $10-19/kWh at cell level claimed, pack-level ~$65/kWh realistic.',
  },
  {
    id: 'cell-byd-naion',
    manufacturer: 'BYD',
    model: 'Sodium-Ion Gen1',
    origin: 'China (Xining)',
    chemistry: 'Na-ion',
    energyDensityWhKg: 160,
    nominalVoltage: 3.1,
    capacityAh: 80,
    cycleLife: 10000,
    operatingTempMin: -40,
    operatingTempMax: 60,
    chargeTempMin: -20,
    chargeTempMax: 55,
    coldPerformanceRetention: 90,
    estimatedCellPriceUsdKwh: 50,
    estimatedPackPriceUsdKwh: 75,
    productionCapacityGwh: 30,
    status: 'mass-production',
    exportToUk: true,
    moqKwh: 1000,
    certifications: ['UN38.3', 'IEC 62619'],
    notes: '30GWh Xining line operational July 2025. 180-200 Wh/kg Gen2 expected 2026. 30% cost reduction vs LFP claimed.',
  },
  {
    id: 'cell-hina-haixing',
    manufacturer: 'HiNa Battery',
    model: 'Haixing K Series',
    origin: 'China',
    chemistry: 'Na-ion',
    energyDensityWhKg: 165,
    nominalVoltage: 3.0,
    capacityAh: 72,
    cycleLife: 8000,
    operatingTempMin: -40,
    operatingTempMax: 45,
    chargeTempMin: -20,
    chargeTempMax: 45,
    fastChargeMinutes: 25,
    estimatedCellPriceUsdKwh: 55,
    estimatedPackPriceUsdKwh: 80,
    productionCapacityGwh: 5,
    status: 'mass-production',
    exportToUk: true,
    moqKwh: 200,
    certifications: ['UN38.3'],
    notes: 'Chinese Na-ion specialist. 5GWh capacity. Already powering JAC Yiwei EV. Can accept global orders.',
  },
  {
    id: 'cell-svolt-naion',
    manufacturer: 'SVOLT',
    model: 'Na-ion Gen1',
    origin: 'China',
    chemistry: 'Na-ion',
    energyDensityWhKg: 110,
    nominalVoltage: 3.0,
    capacityAh: 50,
    cycleLife: 5000,
    operatingTempMin: -30,
    operatingTempMax: 55,
    chargeTempMin: -10,
    chargeTempMax: 45,
    estimatedCellPriceUsdKwh: 60,
    estimatedPackPriceUsdKwh: 90,
    productionCapacityGwh: 2,
    status: 'pilot',
    exportToUk: false,
    certifications: ['UN38.3'],
    notes: 'Focus shifted to semi-solid-state batteries. Na-ion programme deprioritised. 110 Wh/kg first gen only.',
  },
  {
    id: 'cell-faradion',
    manufacturer: 'Faradion (Reliance)',
    model: 'Pouch Cell',
    origin: 'UK/India',
    chemistry: 'Na-ion',
    energyDensityWhKg: 160,
    nominalVoltage: 3.1,
    capacityAh: 30,
    cycleLife: 1000,
    operatingTempMin: -30,
    operatingTempMax: 60,
    chargeTempMin: -10,
    chargeTempMax: 45,
    estimatedCellPriceUsdKwh: 80,
    estimatedPackPriceUsdKwh: 120,
    productionCapacityGwh: 1,
    status: 'pilot',
    exportToUk: true,
    certifications: ['UN38.3'],
    notes: 'UK-origin technology, now owned by Reliance Industries (India). Manufacturing scaling in Jamnagar, India. Low cycle life (1000 at 100% DoD). UK R&D still active.',
  },
  {
    id: 'cell-generic-china',
    manufacturer: 'Various (Alibaba/MiC)',
    model: 'Generic Na-ion 3.0V',
    origin: 'China',
    chemistry: 'Na-ion',
    energyDensityWhKg: 140,
    nominalVoltage: 3.0,
    capacityAh: 50,
    cycleLife: 4000,
    operatingTempMin: -20,
    operatingTempMax: 55,
    chargeTempMin: 0,
    chargeTempMax: 45,
    estimatedCellPriceUsdKwh: 45,
    estimatedPackPriceUsdKwh: 70,
    productionCapacityGwh: 10,
    status: 'mass-production',
    exportToUk: true,
    moqKwh: 50,
    certifications: [],
    notes: 'Various unbranded cells on Alibaba/Made-in-China. Prices $45-70/kWh. Quality variable. Need independent UN38.3 testing. Risk: no warranty backing.',
  },
];

// --- Pack Designs ---

export const packDesigns: PackDesign[] = [
  {
    id: 'pack-5kwh',
    name: 'RoseStack Na5',
    nominalCapacityKwh: 5.12,
    cellsInSeries: 16,
    cellsInParallel: 1,
    totalCells: 16,
    nominalVoltageV: 48,
    maxChargeRateKw: 2.5,
    maxDischargeRateKw: 2.5,
    weightKg: 38,
    dimensionsMm: { width: 440, height: 580, depth: 180 },
    ipRating: 'IP65',
    bmsType: 'JK BMS B2A24S (Na-ion configured)',
    thermalManagement: 'Passive air cooling with thermal pads',
    estimatedBomGbp: 680,
  },
  {
    id: 'pack-8kwh',
    name: 'RoseStack Na8',
    nominalCapacityKwh: 8.19,
    cellsInSeries: 16,
    cellsInParallel: 2,
    totalCells: 32,
    nominalVoltageV: 48,
    maxChargeRateKw: 4.0,
    maxDischargeRateKw: 4.0,
    weightKg: 58,
    dimensionsMm: { width: 440, height: 680, depth: 220 },
    ipRating: 'IP65',
    bmsType: 'JK BMS B2A24S (Na-ion configured)',
    thermalManagement: 'Passive air cooling with thermal pads',
    estimatedBomGbp: 1050,
  },
  {
    id: 'pack-12kwh',
    name: 'RoseStack Na12',
    nominalCapacityKwh: 12.29,
    cellsInSeries: 16,
    cellsInParallel: 3,
    totalCells: 48,
    nominalVoltageV: 48,
    maxChargeRateKw: 6.0,
    maxDischargeRateKw: 6.0,
    weightKg: 82,
    dimensionsMm: { width: 550, height: 780, depth: 260 },
    ipRating: 'IP65',
    bmsType: 'Orion Jr2 (0.5-5.0V per cell)',
    thermalManagement: 'Active fan cooling with thermal pads and heat sink',
    estimatedBomGbp: 1520,
  },
];

// --- BMS Options ---

export const bmsOptions: BmsOption[] = [
  {
    id: 'bms-jk-b2a24s',
    name: 'JK BMS B2A24S',
    manufacturer: 'JK BMS',
    protocol: 'CAN / RS485',
    voltageRangeMin: 1.2,
    voltageRangeMax: 4.35,
    cellCountMax: 24,
    sodiumIonCompatible: true,
    canBus: true,
    rs485: true,
    priceGbp: 85,
    notes: 'Programmable 1.2-4.35V per cell. Works with Na-ion 2.0-3.7V range. CAN bus for Victron/Deye integration. Popular in DIY community.',
  },
  {
    id: 'bms-orion-jr2',
    name: 'Orion Jr2',
    manufacturer: 'Ewert Energy Systems',
    protocol: 'CAN / UART',
    voltageRangeMin: 0.5,
    voltageRangeMax: 5.0,
    cellCountMax: 48,
    sodiumIonCompatible: true,
    canBus: true,
    rs485: false,
    priceGbp: 320,
    notes: 'Professional-grade. 0.5-5.0V range covers all Na-ion chemistries. Up to 48 cells. Victron compatible via CAN bus.',
  },
  {
    id: 'bms-daly-smart',
    name: 'Daly Smart BMS',
    manufacturer: 'Daly Electronics',
    protocol: 'UART / Bluetooth',
    voltageRangeMin: 2.0,
    voltageRangeMax: 4.35,
    cellCountMax: 16,
    sodiumIonCompatible: true,
    canBus: false,
    rs485: true,
    priceGbp: 55,
    notes: 'Budget option. Configurable for Na-ion. No native CAN bus — needs adapter for inverter comms. Bluetooth monitoring.',
  },
];

// --- Inverter Options ---

export const inverterOptions: InverterOption[] = [
  {
    id: 'inv-victron-mp2',
    manufacturer: 'Victron Energy',
    model: 'MultiPlus-II 48/5000',
    type: 'hybrid',
    maxOutputKw: 5.0,
    thirdPartyBattery: true,
    canBmsProtocol: true,
    openProtocol: true,
    iofCompatible: true,
    octopusApiIntegration: true,
    homeAssistantCompatible: true,
    g99Compliant: true,
    priceGbp: 1450,
    sodiumIonCompatibility: 'compatible',
    whiteLabel: false,
    notes: 'Best option for custom batteries. Open CAN protocol via GX device (Venus OS). Victron offers limited support for custom BMS but has active community. BMS must control CVL correctly.',
  },
  {
    id: 'inv-sigenergy-m1',
    manufacturer: 'Sigenergy',
    model: 'SigenStor M1',
    type: 'hybrid',
    maxOutputKw: 6.0,
    thirdPartyBattery: false,
    canBmsProtocol: false,
    openProtocol: false,
    iofCompatible: true,
    octopusApiIntegration: true,
    homeAssistantCompatible: true,
    g99Compliant: true,
    priceGbp: 2200,
    sodiumIonCompatibility: 'incompatible',
    whiteLabel: false,
    notes: 'Closed ecosystem. Only works with SigenStack batteries. Cannot use third-party batteries. Best IOF integration but not suitable for RoseStack own-brand battery.',
  },
  {
    id: 'inv-givenergy',
    manufacturer: 'GivEnergy',
    model: 'Gen 3 Hybrid',
    type: 'hybrid',
    maxOutputKw: 6.0,
    thirdPartyBattery: false,
    canBmsProtocol: false,
    openProtocol: false,
    iofCompatible: true,
    octopusApiIntegration: true,
    homeAssistantCompatible: true,
    g99Compliant: true,
    priceGbp: 1800,
    sodiumIonCompatibility: 'incompatible',
    whiteLabel: false,
    notes: 'Closed ecosystem. GivEnergy inverters only talk to GivEnergy batteries. Not viable for custom battery integration.',
  },
  {
    id: 'inv-deye-hybrid',
    manufacturer: 'Deye',
    model: 'SUN-6K-SG04LP3',
    type: 'hybrid',
    maxOutputKw: 6.0,
    thirdPartyBattery: true,
    canBmsProtocol: true,
    openProtocol: true,
    iofCompatible: false,
    octopusApiIntegration: false,
    homeAssistantCompatible: true,
    g99Compliant: true,
    priceGbp: 950,
    sodiumIonCompatibility: 'native',
    whiteLabel: true,
    notes: 'Industry favourite for Na-ion. Wide DC input range. Specific firmware for sodium batteries. White-label available. Needs Octopus integration via Home Assistant.',
  },
  {
    id: 'inv-growatt-sph',
    manufacturer: 'Growatt',
    model: 'SPH 6000TL3 BH-UP',
    type: 'hybrid',
    maxOutputKw: 6.0,
    thirdPartyBattery: true,
    canBmsProtocol: true,
    openProtocol: false,
    iofCompatible: false,
    octopusApiIntegration: false,
    homeAssistantCompatible: true,
    g99Compliant: true,
    priceGbp: 1100,
    sodiumIonCompatibility: 'possible',
    whiteLabel: true,
    notes: 'Third-party battery via approved list. Na-ion not officially supported but CAN protocol is open enough. White-label option available.',
  },
  {
    id: 'inv-sofar-hyd',
    manufacturer: 'Sofar',
    model: 'HYD 6000-EP',
    type: 'hybrid',
    maxOutputKw: 6.0,
    thirdPartyBattery: true,
    canBmsProtocol: true,
    openProtocol: false,
    iofCompatible: false,
    octopusApiIntegration: false,
    homeAssistantCompatible: true,
    g99Compliant: true,
    priceGbp: 1000,
    sodiumIonCompatibility: 'possible',
    whiteLabel: true,
    notes: 'Open to third-party batteries. White-label programme available from Chinese factory. CAN bus communication for BMS.',
  },
];

// --- Cost Models ---

export const costModels: CostModel[] = [
  {
    id: 'cost-sigenergy-12kwh',
    name: 'Sigenergy SigenStack 12kWh (Incumbent)',
    capacityKwh: 12,
    lineItems: [
      { category: 'Battery', description: 'SigenStack 12kWh module', unitCostGbp: 3542, quantity: 1, totalGbp: 3542 },
      { category: 'Inverter', description: 'SigenStor M1 (included in system)', unitCostGbp: 0, quantity: 1, totalGbp: 0 },
    ],
    totalBomGbp: 3542,
    marginPercent: 0,
    retailPriceGbp: 3542,
    pricePerKwhGbp: 295,
    comparisonRetailGbp: 3542,
    savingsPercent: 0,
  },
  {
    id: 'cost-rosestack-na12-victron',
    name: 'RoseStack Na12 + Victron (Recommended)',
    capacityKwh: 12,
    lineItems: [
      { category: 'Cells', description: 'CATL Naxtra Na-ion cells (48x 3.0V 100Ah)', unitCostGbp: 12, quantity: 48, totalGbp: 576 },
      { category: 'BMS', description: 'Orion Jr2 BMS', unitCostGbp: 320, quantity: 1, totalGbp: 320 },
      { category: 'Enclosure', description: 'IP65 steel enclosure + thermal management', unitCostGbp: 280, quantity: 1, totalGbp: 280 },
      { category: 'Wiring', description: 'Busbars, cables, connectors, fuses', unitCostGbp: 85, quantity: 1, totalGbp: 85 },
      { category: 'Assembly', description: 'UK assembly labour (4 hours)', unitCostGbp: 25, quantity: 4, totalGbp: 100 },
      { category: 'Shipping', description: 'China to UK sea freight per unit (amortised)', unitCostGbp: 45, quantity: 1, totalGbp: 45 },
      { category: 'Testing', description: 'QA testing per unit', unitCostGbp: 35, quantity: 1, totalGbp: 35 },
      { category: 'Certification', description: 'Amortised cert costs (per 1000 units)', unitCostGbp: 120, quantity: 1, totalGbp: 120 },
    ],
    totalBomGbp: 1561,
    marginPercent: 30,
    retailPriceGbp: 2030,
    pricePerKwhGbp: 169,
    comparisonRetailGbp: 3542,
    savingsPercent: 43,
  },
  {
    id: 'cost-rosestack-na12-deye',
    name: 'RoseStack Na12 + Deye (Budget)',
    capacityKwh: 12,
    lineItems: [
      { category: 'Cells', description: 'CATL Naxtra Na-ion cells (48x 3.0V 100Ah)', unitCostGbp: 12, quantity: 48, totalGbp: 576 },
      { category: 'BMS', description: 'JK BMS B2A24S (Na-ion configured)', unitCostGbp: 85, quantity: 1, totalGbp: 85 },
      { category: 'Enclosure', description: 'IP65 steel enclosure + thermal management', unitCostGbp: 280, quantity: 1, totalGbp: 280 },
      { category: 'Wiring', description: 'Busbars, cables, connectors, fuses', unitCostGbp: 85, quantity: 1, totalGbp: 85 },
      { category: 'Assembly', description: 'UK assembly labour (4 hours)', unitCostGbp: 25, quantity: 4, totalGbp: 100 },
      { category: 'Shipping', description: 'China to UK sea freight per unit (amortised)', unitCostGbp: 45, quantity: 1, totalGbp: 45 },
      { category: 'Testing', description: 'QA testing per unit', unitCostGbp: 35, quantity: 1, totalGbp: 35 },
      { category: 'Certification', description: 'Amortised cert costs (per 1000 units)', unitCostGbp: 120, quantity: 1, totalGbp: 120 },
    ],
    totalBomGbp: 1326,
    marginPercent: 30,
    retailPriceGbp: 1724,
    pricePerKwhGbp: 144,
    comparisonRetailGbp: 3542,
    savingsPercent: 51,
  },
  {
    id: 'cost-rosestack-na5-victron',
    name: 'RoseStack Na5 + Victron (Entry)',
    capacityKwh: 5,
    lineItems: [
      { category: 'Cells', description: 'CATL Naxtra Na-ion cells (16x 3.0V 100Ah)', unitCostGbp: 12, quantity: 16, totalGbp: 192 },
      { category: 'BMS', description: 'JK BMS B2A24S (Na-ion configured)', unitCostGbp: 85, quantity: 1, totalGbp: 85 },
      { category: 'Enclosure', description: 'IP65 enclosure + passive cooling', unitCostGbp: 180, quantity: 1, totalGbp: 180 },
      { category: 'Wiring', description: 'Busbars, cables, connectors, fuses', unitCostGbp: 65, quantity: 1, totalGbp: 65 },
      { category: 'Assembly', description: 'UK assembly labour (3 hours)', unitCostGbp: 25, quantity: 3, totalGbp: 75 },
      { category: 'Shipping', description: 'China to UK sea freight per unit (amortised)', unitCostGbp: 30, quantity: 1, totalGbp: 30 },
      { category: 'Testing', description: 'QA testing per unit', unitCostGbp: 25, quantity: 1, totalGbp: 25 },
      { category: 'Certification', description: 'Amortised cert costs (per 1000 units)', unitCostGbp: 80, quantity: 1, totalGbp: 80 },
    ],
    totalBomGbp: 732,
    marginPercent: 30,
    retailPriceGbp: 952,
    pricePerKwhGbp: 190,
    comparisonRetailGbp: 3542,
    savingsPercent: 73,
  },
];

// --- Regulatory Milestones ---

export const regulatoryMilestones: RegulatoryMilestone[] = [
  {
    id: 'reg-un383',
    name: 'UN38.3 Transport Testing',
    description: 'Mandatory safety testing for battery transport by sea/air. Tests include altitude simulation, thermal cycling, vibration, shock, short circuit, impact, overcharge, and forced discharge.',
    standard: 'UN38.3',
    status: 'not-started',
    estimatedCostGbp: 15000,
    estimatedWeeks: 8,
    targetDate: '2027-Q1',
    dependencies: [],
    notes: 'Must be completed before any import shipments. Use accredited UK lab (e.g. Element Materials, TUV). Cost per cell variant.',
  },
  {
    id: 'reg-iec62619',
    name: 'IEC 62619 Safety Certification',
    description: 'Secondary lithium/sodium cells and batteries for industrial applications. Covers safety requirements for stationary use.',
    standard: 'IEC 62619',
    status: 'not-started',
    estimatedCostGbp: 25000,
    estimatedWeeks: 12,
    targetDate: '2027-Q2',
    dependencies: ['reg-un383'],
    notes: 'Required for commercial sale in UK. Testing at pack level. Covers overcharge, short circuit, thermal abuse, crush, drop tests.',
  },
  {
    id: 'reg-ul9540a',
    name: 'UL 9540A Thermal Runaway Testing',
    description: 'Evaluation of thermal runaway fire propagation in battery energy storage systems. Cell-level, module-level, and unit-level testing.',
    standard: 'UL 9540A',
    status: 'not-started',
    estimatedCostGbp: 35000,
    estimatedWeeks: 16,
    targetDate: '2027-Q3',
    dependencies: ['reg-iec62619'],
    notes: 'Critical for insurance and PAS 63100 compliance. Na-ion has inherent safety advantage — lower thermal runaway risk than Li-ion.',
  },
  {
    id: 'reg-pas63100',
    name: 'PAS 63100 Compliance',
    description: 'UK specification for fire safety in installation of domestic battery energy storage systems. Covers installation location, ventilation, fire detection, and containment.',
    standard: 'PAS 63100:2024',
    status: 'not-started',
    estimatedCostGbp: 10000,
    estimatedWeeks: 6,
    targetDate: '2027-Q3',
    dependencies: ['reg-ul9540a'],
    notes: 'Product design must meet PAS 63100 requirements. Now referenced in BS 7671 Chapter 57. Enclosure must meet fire containment specs.',
  },
  {
    id: 'reg-g99',
    name: 'G99 Grid Connection Type Testing',
    description: 'Engineering recommendation for grid connection of generation equipment. Required for all grid-connected battery storage systems in the UK.',
    standard: 'G99',
    status: 'not-started',
    estimatedCostGbp: 20000,
    estimatedWeeks: 10,
    targetDate: '2027-Q2',
    dependencies: [],
    notes: 'Inverter-side requirement. If using Victron/Deye with existing G99 approval, may not need retesting. New inverter would need full G99.',
  },
  {
    id: 'reg-ukca',
    name: 'UKCA Marking',
    description: 'UK Conformity Assessment marking. Required for products sold in Great Britain (England, Wales, Scotland).',
    standard: 'UKCA',
    status: 'not-started',
    estimatedCostGbp: 8000,
    estimatedWeeks: 8,
    targetDate: '2027-Q4',
    dependencies: ['reg-iec62619', 'reg-pas63100'],
    notes: 'Covers EMC, LVD, and product safety directives. Must use UK Approved Body for conformity assessment.',
  },
  {
    id: 'reg-mcs',
    name: 'MCS Product Certification',
    description: 'Microgeneration Certification Scheme product certification. Required for consumer finance eligibility (SEG, ECO4, BUS).',
    standard: 'MIS 3012',
    status: 'not-started',
    estimatedCostGbp: 18000,
    estimatedWeeks: 20,
    targetDate: '2028-Q1',
    dependencies: ['reg-ukca', 'reg-iec62619', 'reg-pas63100'],
    notes: 'Longest lead-time item. Must meet MIS 3012 battery storage standard. Being updated to incorporate PAS 63100. Essential for mainstream installer adoption.',
  },
  {
    id: 'reg-bs7671',
    name: 'BS 7671 Am4 Chapter 57 Compliance',
    description: 'New Chapter 57 in BS 7671 (April 2026) covering stationary battery storage. Includes thermal runaway, safe isolation, location restrictions, fire protection.',
    standard: 'BS 7671:2018+A4:2026',
    status: 'not-started',
    estimatedCostGbp: 5000,
    estimatedWeeks: 4,
    targetDate: '2027-Q1',
    dependencies: [],
    notes: 'Design review against Chapter 57 requirements. Covers installation documentation, thermal runaway mitigation, location restrictions. Effective April 2026.',
  },
  {
    id: 'reg-insurance',
    name: 'Product Liability Insurance',
    description: 'Product liability insurance for a battery manufacturer/assembler. Required before commercial sale.',
    standard: 'N/A',
    status: 'not-started',
    estimatedCostGbp: 12000,
    estimatedWeeks: 6,
    targetDate: '2027-Q4',
    dependencies: ['reg-ul9540a', 'reg-iec62619'],
    notes: 'Annual premium estimate. Insurers will require UL 9540A and IEC 62619 test reports. Na-ion may get favourable terms due to safety profile.',
  },
];

// --- Manufacturing Options ---

export const manufacturingOptions: ManufacturingOption[] = [
  {
    id: 'mfg-full-china',
    strategy: 'full-china-oem',
    name: 'Full Chinese OEM',
    description: 'Design in UK, manufacture complete battery packs in China, ship finished units to UK.',
    cellSource: 'CATL/BYD/HiNa (China)',
    assemblyLocation: 'Shenzhen/Dongguan, China',
    estimatedUnitCostGbp: 1200,
    setupCostGbp: 25000,
    leadTimeWeeks: 12,
    minOrderUnits: 100,
    qualityControl: 'Remote QC + third-party inspection (SGS/Bureau Veritas)',
    brandValue: 'Low — "Made in China" perception',
    grantEligibility: false,
    grantsAvailable: [],
    risks: [
      'Quality control at distance',
      'IP theft risk — design shared with Chinese factory',
      'Supply chain disruption (shipping delays, geopolitics)',
      'Customs duties on finished goods (2.7% + VAT)',
      'Difficult to iterate on design quickly',
    ],
    advantages: [
      'Lowest unit cost',
      'No UK manufacturing overhead',
      'Fast scale-up — Chinese factories can ramp quickly',
      'Established battery pack assembly ecosystem',
      'Access to large pool of skilled battery assembly workers',
    ],
  },
  {
    id: 'mfg-cells-uk-assembly',
    strategy: 'china-cells-uk-assembly',
    name: 'Chinese Cells + UK Assembly',
    description: 'Import bare Na-ion cells from China. Assemble, test, and certify battery packs in Lancashire.',
    cellSource: 'CATL/BYD/HiNa (China)',
    assemblyLocation: 'Lancashire, UK',
    estimatedUnitCostGbp: 1560,
    setupCostGbp: 150000,
    leadTimeWeeks: 16,
    minOrderUnits: 50,
    qualityControl: 'In-house QC + automated testing rig',
    brandValue: 'Medium — "Assembled in Lancashire" + UK quality assurance',
    grantEligibility: true,
    grantsAvailable: [
      'Battery Innovation Programme (up to £4M, 70% costs)',
      'DRIVE35 / APC (automotive R&D)',
      'Lancashire Enterprise Partnership growth grants',
      'UKRI Innovate UK Smart Grants',
    ],
    risks: [
      'Higher unit cost than full China OEM',
      'Need to set up assembly facility (capex)',
      'Cell import still dependent on China supply chain',
      'Skilled battery assembly workers scarce in UK',
      'Regulatory burden as UK manufacturer',
    ],
    advantages: [
      'Full quality control over assembly',
      'IP protection — cell-to-pack design stays in UK',
      'Faster iteration on pack design',
      'Grant eligible — significant funding available',
      '"Made in Lancashire" brand value for local customers',
      'Shorter lead time for UK customers',
      'Jobs created locally — council/community support',
    ],
  },
  {
    id: 'mfg-full-uk',
    strategy: 'full-uk',
    name: 'Full UK Manufacture',
    description: 'Source raw materials, manufacture cells and assemble packs entirely in UK.',
    cellSource: 'UK cell manufacture (hypothetical)',
    assemblyLocation: 'Lancashire, UK',
    estimatedUnitCostGbp: 2800,
    setupCostGbp: 5000000,
    leadTimeWeeks: 52,
    minOrderUnits: 500,
    qualityControl: 'Full in-house QC + cell-level testing',
    brandValue: 'High — "Made in Lancashire" premium brand',
    grantEligibility: true,
    grantsAvailable: [
      'Battery Innovation Programme (up to £4M, 70% costs)',
      'DRIVE35 / APC (up to £4B to 2035)',
      'Faraday Institution research partnerships',
      'UKRI Strength in Places Fund',
      'Levelling Up Fund',
    ],
    risks: [
      'Extremely high capex (>£5M for cell production line)',
      'No UK sodium-ion cell production capability exists',
      'Unit cost 2-3x higher than Chinese cells',
      'Long lead time to establish (12-18 months)',
      'Difficult to compete on price with Chinese imports',
      'Technical expertise for cell manufacturing very scarce in UK',
    ],
    advantages: [
      'Complete supply chain sovereignty',
      'Maximum brand value and story',
      'Maximum grant eligibility',
      'Full IP ownership of cell + pack technology',
      'Zero dependency on Chinese supply chain',
      'Strong ESG and sustainability narrative',
    ],
  },
];

// --- Import Logistics ---

export const importLogistics: ImportLogistics = {
  route: 'Shenzhen/Ningbo → Southampton/Felixstowe (sea freight)',
  shippingCostPerUnit: 45,
  customsDutyPercent: 2.7,
  vatPercent: 20,
  transitDays: 35,
  certifications: [
    'UN38.3 test report (mandatory)',
    'MSDS / SDS (Safety Data Sheet)',
    'Shipping declaration (DGN — Dangerous Goods Note)',
    'IMDG Code compliance (Class 9 — Miscellaneous Dangerous Goods)',
    'CE/UKCA marking documentation',
  ],
  regulations: [
    'UN38.3 testing required before export',
    'IMDG Code Class 9 for sea freight',
    'UK customs declaration — HS code 8507.60 (lithium-ion) or 8507.80 (other)',
    'UKCA marking required for GB market',
    'Product safety — UK Supply of Machinery Regulations',
    'WEEE registration for battery producer responsibility',
    'Battery Regulations 2009 (as amended) — producer registration',
  ],
};
